/*
 * Fragenkatalog für "Der Dümmste fliegt"
 * ---------------------------------------
 * q(kategorie, schwierigkeit, frage, richtigeAntwort, ...falscheAntworten)
 * schwierigkeit: 1 = leicht, 2 = mittel, 3 = schwer
 * Die Antworten werden im Spiel zufällig gemischt.
 */
const q = (k, s, f, r, ...w) => ({ k, s, f, r, w });

window.FRAGEN = [

  /* ---------------- Allgemeinwissen ---------------- */
  q("Allgemeinwissen", 1, "Wie viele Farben hat ein Regenbogen klassischerweise?", "7", "5", "6", "9"),
  q("Allgemeinwissen", 1, "Welche Farbe entsteht, wenn man Blau und Gelb mischt?", "Grün", "Orange", "Lila", "Braun"),
  q("Allgemeinwissen", 1, "Wie viele Buchstaben hat das deutsche Alphabet ohne Umlaute und ß?", "26", "24", "28", "30"),
  q("Allgemeinwissen", 1, "Wie viele Sekunden hat eine Stunde?", "3.600", "360", "6.000", "1.800"),
  q("Allgemeinwissen", 1, "Welches Verkehrsschild ist achteckig?", "Das Stoppschild", "Vorfahrt achten", "Halteverbot", "Einbahnstraße"),
  q("Allgemeinwissen", 1, "Wie viele Bundesländer hat Deutschland?", "16", "14", "17", "12"),
  q("Allgemeinwissen", 1, "Welche Währung gilt in der Schweiz?", "Schweizer Franken", "Euro", "Krone", "Schilling"),
  q("Allgemeinwissen", 1, "Wie viele Karten hat ein deutsches Skatblatt?", "32", "52", "36", "24"),
  q("Allgemeinwissen", 1, "Wie viele Ecken hat ein Würfel?", "8", "6", "12", "4"),
  q("Allgemeinwissen", 1, "Wie viele Nullen hat eine Million?", "6", "3", "9", "12"),
  q("Allgemeinwissen", 1, "Wie viele Grad hat ein voller Kreis?", "360", "180", "270", "400"),
  q("Allgemeinwissen", 1, "Wie viele Felder hat ein Schachbrett?", "64", "48", "81", "100"),
  q("Allgemeinwissen", 2, "Wie viele Bit sind ein Byte?", "8", "4", "16", "10"),
  q("Allgemeinwissen", 2, "Was misst ein Barometer?", "Den Luftdruck", "Die Temperatur", "Die Luftfeuchtigkeit", "Die Windstärke"),
  q("Allgemeinwissen", 2, "Welche römische Zahl steht für 50?", "L", "C", "D", "X"),
  q("Allgemeinwissen", 2, "Wie viele Streifen hat die Flagge der USA?", "13", "50", "12", "15"),
  q("Allgemeinwissen", 2, "Wofür steht die Abkürzung „WLAN“?", "Wireless Local Area Network", "Wide Line Access Network", "Wireless Link And Net", "Web Local Access Node"),
  q("Allgemeinwissen", 2, "Welche Blutgruppe gilt als Universalspender?", "0 negativ", "AB positiv", "A positiv", "B negativ"),
  q("Allgemeinwissen", 2, "Wie viele Zähne hat ein erwachsener Mensch normalerweise?", "32", "28", "30", "36"),
  q("Allgemeinwissen", 2, "Wie viele Grad hat ein rechter Winkel?", "90", "45", "180", "120"),
  q("Allgemeinwissen", 2, "Was bedeutet „ASAP“?", "As soon as possible", "Always send a photo", "As said and posted", "After school, after practice"),
  q("Allgemeinwissen", 2, "Wie viele Sekunden hat ein Tag?", "86.400", "36.000", "144.000", "60.000"),
  q("Allgemeinwissen", 2, "Was bedeutet die Abkürzung „GmbH“?", "Gesellschaft mit beschränkter Haftung", "Gemeinschaft mit betrieblicher Haftung", "Gesellschaft mit betrieblichem Handel", "Genossenschaft mit begrenzter Haftung"),
  q("Allgemeinwissen", 2, "Was bedeutet der Ausdruck „vice versa“?", "Umgekehrt", "Sofort", "Zum Wohl", "Erst recht"),
  q("Allgemeinwissen", 3, "Wie viele Zeitzonen hat Russland?", "11", "7", "9", "14"),
  q("Allgemeinwissen", 3, "Was ist ein Palindrom?", "Ein Wort, das vorwärts wie rückwärts gleich gelesen wird", "Ein Wort mit doppelter Bedeutung", "Ein Wort ohne Vokale", "Ein Wort aus zwei Sprachen"),
  q("Allgemeinwissen", 3, "Welche Farbe hat die sogenannte „Blackbox“ in einem Flugzeug wirklich?", "Orange", "Schwarz", "Rot", "Silber"),
  q("Allgemeinwissen", 3, "Wofür steht „SOS“ ursprünglich?", "Für gar nichts – es ist nur ein einprägsames Morsezeichen", "Save Our Souls", "Send Out Ships", "Stop Other Signals"),
  q("Allgemeinwissen", 3, "Wie viel Prozent der Erdoberfläche sind ungefähr von Wasser bedeckt?", "71 %", "50 %", "61 %", "85 %"),
  q("Allgemeinwissen", 3, "Welches deutsche Gericht entscheidet über Verfassungsfragen?", "Das Bundesverfassungsgericht", "Der Bundesgerichtshof", "Das Bundesverwaltungsgericht", "Der Bundesrat"),

  /* ---------------- Geografie ---------------- */
  q("Geografie", 1, "Wie heißt die Hauptstadt von Italien?", "Rom", "Mailand", "Neapel", "Turin"),
  q("Geografie", 1, "Welcher ist der größte Ozean der Erde?", "Der Pazifik", "Der Atlantik", "Der Indische Ozean", "Das Nordpolarmeer"),
  q("Geografie", 1, "Wie viele Kontinente gibt es?", "7", "5", "6", "8"),
  q("Geografie", 1, "In welcher Stadt steht die Freiheitsstatue?", "New York", "Washington", "Boston", "Philadelphia"),
  q("Geografie", 1, "Welcher Fluss fließt durch Paris?", "Die Seine", "Die Loire", "Die Rhône", "Die Themse"),
  q("Geografie", 1, "Welches Land grenzt im Norden an Deutschland?", "Dänemark", "Norwegen", "Schweden", "Polen"),
  q("Geografie", 1, "Wie heißt der höchste Berg der Welt?", "Mount Everest", "K2", "Mont Blanc", "Kilimandscharo"),
  q("Geografie", 1, "Welcher Kontinent hat die meisten Einwohner?", "Asien", "Afrika", "Europa", "Nordamerika"),
  q("Geografie", 1, "Welche Wüste ist die größte heiße Wüste der Welt?", "Die Sahara", "Die Gobi", "Die Kalahari", "Die Atacama"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Australien?", "Canberra", "Sydney", "Melbourne", "Perth"),
  q("Geografie", 2, "Wie heißt der höchste Berg Deutschlands?", "Die Zugspitze", "Der Brocken", "Der Feldberg", "Der Watzmann"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Kanada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
  q("Geografie", 2, "Wie heißt die Hauptstadt der Türkei?", "Ankara", "Istanbul", "Izmir", "Antalya"),
  q("Geografie", 2, "Welches Land hat heute die meisten Einwohner?", "Indien", "China", "USA", "Indonesien"),
  q("Geografie", 2, "In welchem Land liegt die Stadt Marrakesch?", "Marokko", "Ägypten", "Tunesien", "Algerien"),
  q("Geografie", 2, "Welches Meer liegt zwischen Europa und Afrika?", "Das Mittelmeer", "Das Schwarze Meer", "Das Rote Meer", "Die Nordsee"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Brasilien?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"),
  q("Geografie", 2, "Wie viele Sterne hat die Flagge der Europäischen Union?", "12", "15", "27", "9"),
  q("Geografie", 2, "Welcher Fluss fließt durch Wien?", "Die Donau", "Der Rhein", "Die Elbe", "Die Mosel"),
  q("Geografie", 2, "Welcher Fluss ist auf deutschem Gebiet am längsten?", "Der Rhein", "Die Elbe", "Die Donau", "Die Weser"),
  q("Geografie", 3, "Welches ist das flächenmäßig kleinste Land der Welt?", "Vatikanstadt", "Monaco", "San Marino", "Liechtenstein"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Neuseeland?", "Wellington", "Auckland", "Christchurch", "Dunedin"),
  q("Geografie", 3, "Welches Land hat die längste Küstenlinie der Welt?", "Kanada", "Russland", "Australien", "Indonesien"),
  q("Geografie", 3, "In welchem Bundesland liegt Erfurt?", "Thüringen", "Sachsen", "Sachsen-Anhalt", "Hessen"),
  q("Geografie", 3, "Welches Land wird „Land der tausend Seen“ genannt?", "Finnland", "Schweden", "Kanada", "Estland"),
  q("Geografie", 3, "Welche Meerenge trennt Europa von Afrika?", "Die Straße von Gibraltar", "Der Bosporus", "Der Ärmelkanal", "Die Straße von Hormus"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Kasachstan?", "Astana", "Almaty", "Taschkent", "Bischkek"),
  q("Geografie", 3, "Welcher See ist der tiefste der Welt?", "Der Baikalsee", "Der Titicacasee", "Der Viktoriasee", "Der Kaspische See"),
  q("Geografie", 3, "An welches einzige Land grenzt Portugal?", "Spanien", "Frankreich", "Marokko", "Andorra"),
  q("Geografie", 3, "Welcher See ist der größte, der vollständig in Deutschland liegt?", "Die Müritz", "Der Bodensee", "Der Chiemsee", "Der Starnberger See"),

  /* ---------------- Geschichte ---------------- */
  q("Geschichte", 1, "In welchem Jahr fiel die Berliner Mauer?", "1989", "1987", "1990", "1991"),
  q("Geschichte", 1, "In welchem Jahr begann der Zweite Weltkrieg?", "1939", "1938", "1940", "1941"),
  q("Geschichte", 1, "Wer betrat 1969 als erster Mensch den Mond?", "Neil Armstrong", "Buzz Aldrin", "Juri Gagarin", "Michael Collins"),
  q("Geschichte", 1, "In welchem Jahr wurde Deutschland wiedervereinigt?", "1990", "1989", "1991", "1992"),
  q("Geschichte", 1, "Welches berühmte Schiff sank im Jahr 1912?", "Die Titanic", "Die Lusitania", "Die Bismarck", "Die Mary Rose"),
  q("Geschichte", 1, "Wer war die erste Bundeskanzlerin Deutschlands?", "Angela Merkel", "Annalena Baerbock", "Ursula von der Leyen", "Hannelore Kraft"),
  q("Geschichte", 1, "Wer war der erste Präsident der USA?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"),
  q("Geschichte", 2, "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", "Konrad Adenauer", "Ludwig Erhard", "Willy Brandt", "Helmut Schmidt"),
  q("Geschichte", 2, "Wer gilt als der erste römische Kaiser?", "Augustus", "Julius Caesar", "Nero", "Konstantin"),
  q("Geschichte", 2, "In welchem Jahr endete der Erste Weltkrieg?", "1918", "1916", "1919", "1920"),
  q("Geschichte", 2, "Wer erfand in Europa den Buchdruck mit beweglichen Lettern?", "Johannes Gutenberg", "Martin Luther", "Leonardo da Vinci", "Nikolaus Kopernikus"),
  q("Geschichte", 2, "In welchem Jahr erreichte Christoph Kolumbus Amerika?", "1492", "1453", "1517", "1520"),
  q("Geschichte", 2, "Wessen Grab entdeckte Howard Carter im Jahr 1922?", "Tutanchamun", "Ramses II.", "Cheops", "Echnaton"),
  q("Geschichte", 2, "Was schlug Martin Luther 1517 in Wittenberg an?", "95 Thesen", "Die Bibelübersetzung", "Den Augsburger Religionsfrieden", "Die Goldene Bulle"),
  q("Geschichte", 2, "Wie nennt man die Zeit der Ost-West-Spannungen nach 1945?", "Der Kalte Krieg", "Die Restauration", "Die Blockzeit", "Der Stellungskrieg"),
  q("Geschichte", 2, "Wie hieß der berühmte Anführer der Hunnen?", "Attila", "Dschingis Khan", "Hannibal", "Spartacus"),
  q("Geschichte", 2, "Wer war Bundeskanzler zur Zeit der deutschen Wiedervereinigung?", "Helmut Kohl", "Gerhard Schröder", "Helmut Schmidt", "Willy Brandt"),
  q("Geschichte", 3, "Wer war der letzte deutsche Kaiser?", "Wilhelm II.", "Friedrich III.", "Wilhelm I.", "Ludwig II."),
  q("Geschichte", 3, "In welchem Jahr wurde die DDR gegründet?", "1949", "1945", "1953", "1961"),
  q("Geschichte", 3, "Mit wem schrieb Friedrich Engels das „Kommunistische Manifest“?", "Karl Marx", "Lenin", "Rosa Luxemburg", "August Bebel"),
  q("Geschichte", 3, "Welches antike Weltwunder stand in Alexandria?", "Der Leuchtturm von Pharos", "Der Koloss von Rhodos", "Die Hängenden Gärten", "Der Zeus-Tempel"),
  q("Geschichte", 3, "In welchem Jahr stürmten Pariser die Bastille?", "1789", "1776", "1799", "1815"),
  q("Geschichte", 3, "Bei welcher Schlacht erlitt Napoleon 1815 seine endgültige Niederlage?", "Bei Waterloo", "Bei Leipzig", "Bei Austerlitz", "Bei Trafalgar"),
  q("Geschichte", 3, "Wie hieß der erste künstliche Satellit der Erde?", "Sputnik 1", "Apollo 1", "Explorer 1", "Wostok 1"),
  q("Geschichte", 3, "Welche Stadt wurde 79 n. Chr. durch den Ausbruch des Vesuvs verschüttet?", "Pompeji", "Rom", "Neapel", "Karthago"),
  q("Geschichte", 3, "In welchem Jahr wurde die Berliner Mauer gebaut?", "1961", "1949", "1953", "1968"),
  q("Geschichte", 3, "Welche Königsdynastie herrschte in Frankreich vor der Revolution?", "Die Bourbonen", "Die Habsburger", "Die Tudors", "Die Romanows"),
  q("Geschichte", 3, "In welchem Jahrhundert lebte Martin Luther?", "Im 16. Jahrhundert", "Im 14. Jahrhundert", "Im 15. Jahrhundert", "Im 17. Jahrhundert"),
  q("Geschichte", 3, "Welche britische Königin regierte von 1952 bis 2022?", "Elizabeth II.", "Victoria", "Elizabeth I.", "Mary II."),
  q("Geschichte", 3, "In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?", "1949", "1945", "1948", "1950"),

  /* ---------------- Wissenschaft ---------------- */
  q("Wissenschaft", 1, "Welche chemische Formel hat Wasser?", "H₂O", "CO₂", "O₂", "H₂O₂"),
  q("Wissenschaft", 1, "Wie viele Planeten hat unser Sonnensystem?", "8", "9", "7", "10"),
  q("Wissenschaft", 1, "Welcher Planet ist der Sonne am nächsten?", "Merkur", "Venus", "Mars", "Erde"),
  q("Wissenschaft", 1, "Was ist das größte Organ des Menschen?", "Die Haut", "Die Leber", "Die Lunge", "Der Darm"),
  q("Wissenschaft", 1, "Welcher Planet wird auch „der rote Planet“ genannt?", "Mars", "Jupiter", "Venus", "Merkur"),
  q("Wissenschaft", 1, "Wie heißt die Galaxie, in der wir leben?", "Die Milchstraße", "Andromeda", "Der Orionnebel", "Die Magellansche Wolke"),
  q("Wissenschaft", 1, "Wie heißt der größte Planet unseres Sonnensystems?", "Jupiter", "Saturn", "Neptun", "Uranus"),
  q("Wissenschaft", 1, "Wie nennt man den Vorgang, bei dem Pflanzen Licht in Energie umwandeln?", "Fotosynthese", "Osmose", "Verdunstung", "Zellatmung"),
  q("Wissenschaft", 1, "Bei wie viel Grad Celsius siedet Wasser auf Meereshöhe?", "100", "90", "80", "120"),
  q("Wissenschaft", 2, "Welches chemische Symbol steht für Gold?", "Au", "Ag", "Go", "Gd"),
  q("Wissenschaft", 2, "Wie schnell ist Licht ungefähr?", "300.000 km/s", "3.000 km/s", "30.000 km/s", "3 Mio. km/s"),
  q("Wissenschaft", 2, "Wer entwickelte die Relativitätstheorie?", "Albert Einstein", "Isaac Newton", "Max Planck", "Niels Bohr"),
  q("Wissenschaft", 2, "Wie viele Chromosomenpaare hat ein Mensch?", "23", "24", "46", "12"),
  q("Wissenschaft", 2, "Was misst die Einheit Hertz?", "Die Frequenz", "Die Lautstärke", "Die Spannung", "Die Leistung"),
  q("Wissenschaft", 2, "Welches Element hat die Ordnungszahl 1?", "Wasserstoff", "Helium", "Sauerstoff", "Kohlenstoff"),
  q("Wissenschaft", 2, "Wofür steht die Abkürzung „CPU“?", "Central Processing Unit", "Computer Power Unit", "Control Program Unit", "Central Program Utility"),
  q("Wissenschaft", 2, "Wie viele Knochen hat ein erwachsener Mensch ungefähr?", "206", "150", "300", "412"),
  q("Wissenschaft", 2, "Welches Teilchen im Atom ist negativ geladen?", "Das Elektron", "Das Proton", "Das Neutron", "Das Photon"),
  q("Wissenschaft", 2, "Welche Einheit misst die elektrische Spannung?", "Volt", "Ampere", "Watt", "Ohm"),
  q("Wissenschaft", 2, "Welcher Naturforscher formulierte die Evolutionstheorie?", "Charles Darwin", "Gregor Mendel", "Carl von Linné", "Alexander von Humboldt"),
  q("Wissenschaft", 3, "Welches Metall ist bei Zimmertemperatur flüssig?", "Quecksilber", "Blei", "Zinn", "Natrium"),
  q("Wissenschaft", 3, "Welches Gas macht den größten Anteil unserer Atemluft aus?", "Stickstoff", "Sauerstoff", "Kohlendioxid", "Argon"),
  q("Wissenschaft", 3, "Was entdeckte Alexander Fleming im Jahr 1928?", "Penicillin", "Insulin", "Die Röntgenstrahlung", "Die DNA-Struktur"),
  q("Wissenschaft", 3, "Wie viel Prozent Sauerstoff enthält die Luft ungefähr?", "21 %", "35 %", "50 %", "78 %"),
  q("Wissenschaft", 3, "Wofür steht die Abkürzung „DNA“ im Deutschen?", "Desoxyribonukleinsäure", "Dinatriumacetat", "Doppelnukleinsäure", "Diaminonukleosid"),
  q("Wissenschaft", 3, "Welche Blutgefäße transportieren Blut vom Herzen weg?", "Arterien", "Venen", "Kapillaren", "Lymphgefäße"),
  q("Wissenschaft", 3, "Welcher Stoff ist im Universum am häufigsten?", "Wasserstoff", "Sauerstoff", "Helium", "Eisen"),
  q("Wissenschaft", 3, "Wie heißt die Wissenschaft, die Erdbeben erforscht?", "Seismologie", "Geodäsie", "Vulkanologie", "Meteorologie"),
  q("Wissenschaft", 3, "Wie nennt man die kleinste Einheit eines chemischen Elements?", "Das Atom", "Das Molekül", "Die Zelle", "Das Ion"),
  q("Wissenschaft", 3, "Welcher Planet hat das auffälligste Ringsystem?", "Saturn", "Jupiter", "Uranus", "Neptun"),

  /* ---------------- Sport ---------------- */
  q("Sport", 1, "Wie viele Spieler einer Fußballmannschaft stehen auf dem Platz?", "11", "10", "12", "9"),
  q("Sport", 1, "Wie lange dauert ein Fußballspiel regulär?", "90 Minuten", "60 Minuten", "80 Minuten", "120 Minuten"),
  q("Sport", 1, "Alle wie viele Jahre finden die Olympischen Sommerspiele statt?", "Alle 4 Jahre", "Alle 2 Jahre", "Alle 3 Jahre", "Alle 5 Jahre"),
  q("Sport", 1, "Wie viele Ringe hat das olympische Symbol?", "5", "4", "6", "3"),
  q("Sport", 1, "Wie viele Spieler einer Basketballmannschaft stehen auf dem Feld?", "5", "6", "7", "4"),
  q("Sport", 2, "Welches Land wurde 2014 Fußballweltmeister?", "Deutschland", "Argentinien", "Brasilien", "Spanien"),
  q("Sport", 2, "In welcher Sportart gibt es Grand-Slam-Turniere in Melbourne, Paris, London und New York?", "Tennis", "Golf", "Badminton", "Tischtennis"),
  q("Sport", 2, "Wie viele Punkte bringt ein Touchdown im American Football?", "6", "7", "3", "5"),
  q("Sport", 2, "Wie lang ist ein Marathon?", "42,195 km", "40 km", "45 km", "21,1 km"),
  q("Sport", 2, "In welchem Land fand die Fußball-WM 2018 statt?", "Russland", "Brasilien", "Katar", "Südafrika"),
  q("Sport", 2, "Wie viele Spieler einer Handballmannschaft stehen auf dem Feld?", "7", "6", "8", "5"),
  q("Sport", 2, "Auf welchem Gerät fährt man eine „Halfpipe“?", "Snowboard", "Rennrad", "Schlitten", "Skier mit Stöcken"),
  q("Sport", 2, "Welcher Verein ist deutscher Rekordmeister im Fußball?", "FC Bayern München", "Borussia Dortmund", "Hamburger SV", "FC Schalke 04"),
  q("Sport", 3, "Welcher Fußballer wurde „der Kaiser“ genannt?", "Franz Beckenbauer", "Gerd Müller", "Uwe Seeler", "Lothar Matthäus"),
  q("Sport", 3, "Aus wie vielen Löchern besteht eine Standard-Golfrunde?", "18", "9", "12", "24"),
  q("Sport", 3, "In welcher Sportart wurde Michael Schumacher siebenfacher Weltmeister?", "Formel 1", "MotoGP", "Rallye", "Superbike"),
  q("Sport", 3, "Welche Farbe hat das Trikot des Gesamtführenden bei der Tour de France?", "Gelb", "Grün", "Weiß", "Rot gepunktet"),
  q("Sport", 3, "Wie viele Spieler einer Volleyballmannschaft stehen auf dem Feld?", "6", "5", "7", "8"),
  q("Sport", 3, "Welches Land hat die meisten Fußball-Weltmeistertitel?", "Brasilien", "Deutschland", "Italien", "Argentinien"),
  q("Sport", 3, "Wie lange dauert ein Drittel im Eishockey?", "20 Minuten", "15 Minuten", "25 Minuten", "30 Minuten"),
  q("Sport", 3, "In welcher Höhe hängt ein Basketballkorb?", "3,05 m", "2,80 m", "3,50 m", "2,50 m"),
  q("Sport", 3, "In welcher Stadt fanden die Olympischen Sommerspiele 2021 statt?", "Tokio", "Peking", "Paris", "Rio de Janeiro"),
  q("Sport", 3, "Welcher Boxer nannte sich selbst „The Greatest“?", "Muhammad Ali", "Mike Tyson", "Joe Frazier", "George Foreman"),
  q("Sport", 3, "Wie viele Runden dauert ein WM-Boxkampf maximal?", "12", "10", "15", "8"),
  q("Sport", 3, "In welcher Stadt findet das Tennisturnier Wimbledon statt?", "London", "Manchester", "Melbourne", "Paris"),
  q("Sport", 3, "Wie viele Steine spielt ein Curling-Team pro End?", "8", "6", "10", "4"),
  q("Sport", 3, "Wie viele Gewinnsätze braucht ein Herren-Match bei einem Grand-Slam-Turnier?", "3", "2", "4", "5"),
  q("Sport", 3, "Welche Sportart wird bei der „Vierschanzentournee“ ausgeübt?", "Skispringen", "Abfahrtslauf", "Biathlon", "Bobfahren"),

  /* ---------------- Musik ---------------- */
  q("Musik", 1, "Wie viele Tasten hat ein Standard-Klavier?", "88", "76", "64", "100"),
  q("Musik", 1, "Welche Band sang „Bohemian Rhapsody“?", "Queen", "The Beatles", "Pink Floyd", "The Rolling Stones"),
  q("Musik", 1, "Wie viele Saiten hat eine klassische Gitarre?", "6", "4", "7", "12"),
  q("Musik", 1, "Wie nennt man die Person, die vor einem Orchester den Taktstock schwingt?", "Dirigent", "Komponist", "Solist", "Intendant"),
  q("Musik", 2, "Wer ist als „King of Pop“ bekannt?", "Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"),
  q("Musik", 2, "Aus welcher Stadt stammen die Beatles?", "Liverpool", "London", "Manchester", "Birmingham"),
  q("Musik", 2, "Welches Instrument spielte Louis Armstrong?", "Trompete", "Saxofon", "Klavier", "Kontrabass"),
  q("Musik", 2, "Welche deutsche Band singt „Du hast“?", "Rammstein", "Die Toten Hosen", "Scorpions", "Die Ärzte"),
  q("Musik", 2, "Welche Sängerin veröffentlichte das Album „21“?", "Adele", "Amy Winehouse", "Beyoncé", "Rihanna"),
  q("Musik", 2, "Wie heißt der größte Musikwettbewerb Europas?", "Eurovision Song Contest", "MTV Europe Awards", "Grammy Europe", "Echo Festival"),
  q("Musik", 2, "Welche Sängerin ist für „Bad Romance“ bekannt?", "Lady Gaga", "Katy Perry", "Britney Spears", "Madonna"),
  q("Musik", 2, "Welche Band veröffentlichte „Smells Like Teen Spirit“?", "Nirvana", "Pearl Jam", "Soundgarden", "Green Day"),
  q("Musik", 2, "Aus wie vielen Mitgliedern bestanden die Beatles?", "4", "3", "5", "6"),
  q("Musik", 3, "Wer komponierte die Neunte Sinfonie mit der „Ode an die Freude“?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"),
  q("Musik", 3, "Wer komponierte die Oper „Die Zauberflöte“?", "Wolfgang Amadeus Mozart", "Richard Wagner", "Giuseppe Verdi", "Joseph Haydn"),
  q("Musik", 3, "Wie nennt man ein Musikstück für vier Instrumente?", "Quartett", "Trio", "Quintett", "Duett"),
  q("Musik", 3, "Welcher Künstler sang „Purple Rain“?", "Prince", "Jimi Hendrix", "David Bowie", "Stevie Wonder"),
  q("Musik", 3, "Welche Band veröffentlichte „Stairway to Heaven“?", "Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"),
  q("Musik", 3, "Wer sang „Like a Rolling Stone“?", "Bob Dylan", "Neil Young", "Bruce Springsteen", "Johnny Cash"),
  q("Musik", 3, "Was bedeutet die Vortragsbezeichnung „forte“?", "Laut", "Leise", "Schnell", "Langsam"),
  q("Musik", 3, "Wer komponierte „Die vier Jahreszeiten“?", "Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Johann Pachelbel"),
  q("Musik", 3, "Was bedeutet „a cappella“?", "Gesang ohne Instrumentalbegleitung", "Gesang im Duett", "Sehr hoher Gesang", "Gesang in Latein"),
  q("Musik", 3, "Welcher Musiker wurde „Godfather of Soul“ genannt?", "James Brown", "Marvin Gaye", "Ray Charles", "Otis Redding"),
  q("Musik", 3, "Welches Album ist das meistverkaufte aller Zeiten?", "„Thriller“ von Michael Jackson", "„Back in Black“ von AC/DC", "„The Dark Side of the Moon“", "„Abbey Road“"),
  q("Musik", 3, "Welche Tonart hat weder Kreuze noch Bs?", "C-Dur", "G-Dur", "F-Dur", "D-Dur"),
  q("Musik", 3, "Aus welchem Land stammt der Tango ursprünglich?", "Argentinien", "Spanien", "Brasilien", "Kuba"),

  /* ---------------- Film & TV ---------------- */
  q("Film & TV", 1, "Wie heißt der Zauberschüler aus den Romanen von J. K. Rowling?", "Harry Potter", "Percy Jackson", "Ron Weasley", "Frodo Beutlin"),
  q("Film & TV", 1, "In welcher Filmreihe sagt man „Möge die Macht mit dir sein“?", "Star Wars", "Star Trek", "Herr der Ringe", "Dune"),
  q("Film & TV", 1, "Wie heißt der gelbe Schwamm aus der Zeichentrickserie?", "SpongeBob Schwammkopf", "Patrick Star", "Thaddäus", "Sandy"),
  q("Film & TV", 1, "Wie heißt der junge Löwe in „Der König der Löwen“?", "Simba", "Mufasa", "Scar", "Nala"),
  q("Film & TV", 1, "Wie heißt der Clownfisch, der im Pixar-Film gesucht wird?", "Nemo", "Dorie", "Marlin", "Flunder"),
  q("Film & TV", 1, "Wie heißt der grüne Oger aus dem DreamWorks-Film?", "Shrek", "Fiona", "Donkey", "Gru"),
  q("Film & TV", 2, "Wer spielte Jack in „Titanic“?", "Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"),
  q("Film & TV", 2, "In welcher Stadt spielt die Serie „Friends“?", "New York", "Los Angeles", "Chicago", "Boston"),
  q("Film & TV", 2, "Welcher Schauspieler spielte den ersten Iron Man im Marvel-Universum?", "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"),
  q("Film & TV", 2, "Welcher Hobbit bringt den Ring nach Mordor?", "Frodo Beutlin", "Samweis Gamdschie", "Bilbo Beutlin", "Meriadoc Brandybock"),
  q("Film & TV", 2, "Welche Zeichentrickfamilie lebt in Springfield?", "Die Simpsons", "Die Griffins", "Die Flintstones", "South Park"),
  q("Film & TV", 2, "Wie heißt der Superheld aus Gotham City?", "Batman", "Superman", "Spider-Man", "Iron Man"),
  q("Film & TV", 2, "Welcher Streamingdienst produzierte „Squid Game“?", "Netflix", "Amazon Prime Video", "Disney+", "HBO Max"),
  q("Film & TV", 2, "Welcher Film gewann 2020 den Oscar als bester Film?", "Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"),
  q("Film & TV", 3, "Wer führte Regie bei „Der weiße Hai“?", "Steven Spielberg", "Ridley Scott", "James Cameron", "Martin Scorsese"),
  q("Film & TV", 3, "In welcher Kleinstadt spielt „Stranger Things“?", "Hawkins", "Derry", "Twin Peaks", "Riverdale"),
  q("Film & TV", 3, "Welcher Schauspieler spielt „John Wick“?", "Keanu Reeves", "Liam Neeson", "Jason Statham", "Tom Hardy"),
  q("Film & TV", 3, "Wie heißt der Chemielehrer, der in „Breaking Bad“ zum Drogenkoch wird?", "Walter White", "Jesse Pinkman", "Saul Goodman", "Gus Fring"),
  q("Film & TV", 3, "Wie heißt der Zauberer aus „Der Herr der Ringe“, der grau und später weiß ist?", "Gandalf", "Saruman", "Radagast", "Elrond"),
  q("Film & TV", 3, "In welcher Serie kämpfen Adelshäuser um den Eisernen Thron?", "Game of Thrones", "Vikings", "The Witcher", "The Last Kingdom"),
  q("Film & TV", 3, "Wer moderierte jahrzehntelang „Wetten, dass..?“", "Thomas Gottschalk", "Günther Jauch", "Frank Elstner", "Markus Lanz"),
  q("Film & TV", 3, "Welches Studio produzierte „Toy Story“?", "Pixar", "DreamWorks", "Illumination", "Blue Sky"),
  q("Film & TV", 3, "Wie heißt der Bösewicht in „Der König der Löwen“?", "Scar", "Shere Khan", "Zazu", "Rafiki"),
  q("Film & TV", 3, "Welcher Regisseur drehte „Inception“ und „Interstellar“?", "Christopher Nolan", "Denis Villeneuve", "Quentin Tarantino", "David Fincher"),
  q("Film & TV", 3, "Welche deutsche Netflix-Serie spielt in der Stadt Winden?", "Dark", "Biohackers", "How to Sell Drugs Online (Fast)", "Barbaren"),
  q("Film & TV", 3, "Aus wie vielen Filmen besteht die „Der Herr der Ringe“-Trilogie?", "3", "2", "4", "6"),
  q("Film & TV", 3, "Wie heißt der Droide aus „Star Wars“, der wie eine Mülltonne aussieht?", "R2-D2", "C-3PO", "BB-8", "K-2SO"),
  q("Film & TV", 3, "Auf welchem Mond spielt der Film „Avatar“?", "Pandora", "Arrakis", "Endor", "Titan"),

  /* ---------------- Gaming & Internet ---------------- */
  q("Gaming & Internet", 1, "Wie heißt der berühmte Klempner aus den Nintendo-Spielen?", "Mario", "Luigi", "Link", "Sonic"),
  q("Gaming & Internet", 1, "In welchem Spiel muss man sich vor „Creepern“ in Acht nehmen?", "Minecraft", "Roblox", "Terraria", "Fortnite"),
  q("Gaming & Internet", 1, "Wie heißt das gelbe Elektro-Pokémon?", "Pikachu", "Raichu", "Glumanda", "Evoli"),
  q("Gaming & Internet", 1, "Wie heißt der blaue Igel von Sega?", "Sonic", "Tails", "Knuckles", "Shadow"),
  q("Gaming & Internet", 2, "Welche Firma entwickelt „Fortnite“?", "Epic Games", "Activision", "Ubisoft", "Valve"),
  q("Gaming & Internet", 2, "Welche Konsole brachte Sony 1994 auf den Markt?", "Die PlayStation", "Die Xbox", "Das Nintendo 64", "Den Game Boy"),
  q("Gaming & Internet", 2, "Wofür steht „NPC“ in Videospielen?", "Non-Player Character", "New Player Class", "Network Player Client", "Non-Playable Console"),
  q("Gaming & Internet", 2, "Welche Spielereihe spielt im Königreich Hyrule?", "The Legend of Zelda", "Final Fantasy", "Dark Souls", "Metroid"),
  q("Gaming & Internet", 2, "Welche Livestreaming-Plattform für Games gehört zu Amazon?", "Twitch", "YouTube Gaming", "Kick", "Trovo"),
  q("Gaming & Internet", 2, "Welcher Chat-Dienst ist besonders bei Gamern beliebt?", "Discord", "Slack", "Telegram", "Signal"),
  q("Gaming & Internet", 2, "Welches soziale Netzwerk gehört neben WhatsApp und Facebook zu Meta?", "Instagram", "TikTok", "Snapchat", "X"),
  q("Gaming & Internet", 2, "Wie heißt Nintendos Konsole aus dem Jahr 2017?", "Nintendo Switch", "Wii U", "Nintendo DS", "GameCube"),
  q("Gaming & Internet", 3, "Wer gründete Microsoft zusammen mit Paul Allen?", "Bill Gates", "Steve Jobs", "Steve Ballmer", "Larry Page"),
  q("Gaming & Internet", 3, "Was bedeutet „GG“ im Gaming-Chat?", "Good Game", "Great Gamer", "Go Go", "Got Gold"),
  q("Gaming & Internet", 3, "Welches Studio entwickelt „League of Legends“?", "Riot Games", "Blizzard", "Valve", "Bungie"),
  q("Gaming & Internet", 3, "Was bedeutet „Lag“ in Onlinespielen?", "Eine Verzögerung der Verbindung", "Ein Spielabsturz", "Ein Levelaufstieg", "Ein Cheat"),
  q("Gaming & Internet", 3, "Welches Spiel machte den Battle-Royale-Modus mit 100 Spielern populär?", "PUBG", "Overwatch", "Rust", "Apex Legends"),
  q("Gaming & Internet", 3, "Welche Firma stellt die GeForce-Grafikkarten her?", "Nvidia", "AMD", "Intel", "Qualcomm"),
  q("Gaming & Internet", 3, "Wofür steht „URL“?", "Uniform Resource Locator", "Universal Reference Link", "User Request Line", "Unified Router Location"),
  q("Gaming & Internet", 3, "Welches Unternehmen kaufte YouTube im Jahr 2006?", "Google", "Yahoo", "Microsoft", "Facebook"),
  q("Gaming & Internet", 3, "Welche Shooter-Reihe hat den Untertitel „Modern Warfare“?", "Call of Duty", "Battlefield", "Medal of Honor", "Counter-Strike"),
  q("Gaming & Internet", 3, "Welches Videospiel mit fallenden Blöcken stammt aus der Sowjetunion?", "Tetris", "Pac-Man", "Snake", "Breakout"),
  q("Gaming & Internet", 3, "In welcher fiktiven Stadt spielt „GTA V“?", "Los Santos", "Vice City", "Liberty City", "San Fierro"),
  q("Gaming & Internet", 3, "Was ist ein „Speedrun“?", "Ein Spiel so schnell wie möglich durchspielen", "Ein Rennspielmodus", "Ein Turnier über 24 Stunden", "Ein Sprint-Minispiel"),
  q("Gaming & Internet", 3, "Wie hieß Nintendos Handheld-Konsole von 1989?", "Der Game Boy", "Der Nintendo DS", "Die PSP", "Das Game Gear"),
  q("Gaming & Internet", 3, "Wofür steht die Abkürzung „AFK“?", "Away From Keyboard", "All For Kills", "Away For Knowledge", "After Kill"),

  /* ---------------- Essen & Trinken ---------------- */
  q("Essen & Trinken", 1, "Aus welcher Frucht wird Guacamole hauptsächlich gemacht?", "Avocado", "Gurke", "Zucchini", "Limette"),
  q("Essen & Trinken", 1, "Aus welchem Land stammt die Pizza ursprünglich?", "Italien", "Griechenland", "Spanien", "Frankreich"),
  q("Essen & Trinken", 1, "Welches Gemüse treibt einem beim Schneiden Tränen in die Augen?", "Zwiebel", "Lauch", "Paprika", "Sellerie"),
  q("Essen & Trinken", 1, "Aus welcher Bohne wird Schokolade hergestellt?", "Kakaobohne", "Sojabohne", "Vanillebohne", "Kaffeebohne"),
  q("Essen & Trinken", 2, "Welches Gewürz ist das teuerste der Welt?", "Safran", "Vanille", "Kardamom", "Pfeffer"),
  q("Essen & Trinken", 2, "Woraus wird Sauerkraut hergestellt?", "Weißkohl", "Rotkohl", "Spitzkohl", "Chinakohl"),
  q("Essen & Trinken", 2, "Zu welcher Obstsorte gehört „Granny Smith“?", "Apfel", "Birne", "Pflaume", "Traube"),
  q("Essen & Trinken", 2, "Wie heißt der scharfe grüne japanische Meerrettich?", "Wasabi", "Ingwer", "Miso", "Yuzu"),
  q("Essen & Trinken", 2, "Aus welchem Land stammt Feta-Käse?", "Griechenland", "Italien", "Türkei", "Bulgarien"),
  q("Essen & Trinken", 2, "Von welchem Tier stammt die Milch für original Mozzarella di Bufala?", "Vom Wasserbüffel", "Von der Kuh", "Von der Ziege", "Vom Schaf"),
  q("Essen & Trinken", 2, "Welche Frucht wird auch „Chinesische Stachelbeere“ genannt?", "Kiwi", "Litschi", "Mango", "Papaya"),
  q("Essen & Trinken", 3, "Welches Land produziert weltweit den meisten Kaffee?", "Brasilien", "Kolumbien", "Vietnam", "Äthiopien"),
  q("Essen & Trinken", 3, "Woraus wird Tofu hergestellt?", "Aus Sojabohnen", "Aus Kichererbsen", "Aus Weizen", "Aus Reis"),
  q("Essen & Trinken", 3, "Welche Nudelsorte ist röhrenförmig und schräg abgeschnitten?", "Penne", "Farfalle", "Fusilli", "Tagliatelle"),
  q("Essen & Trinken", 3, "Was ist die Hauptzutat von Hummus?", "Kichererbsen", "Linsen", "Bohnen", "Erbsen"),
  q("Essen & Trinken", 3, "Aus welcher Pflanze wird Tequila hergestellt?", "Aus der Agave", "Aus Zuckerrohr", "Aus Kaktusfeigen", "Aus Mais"),
  q("Essen & Trinken", 3, "Welche Stadt gilt als Heimat der Currywurst?", "Berlin", "Hamburg", "Bochum", "Köln"),
  q("Essen & Trinken", 3, "Wie viel Alkohol hat ein typisches deutsches Pils ungefähr?", "5 %", "8 %", "12 %", "2 %"),
  q("Essen & Trinken", 3, "Aus welchem Getreide besteht Bulgur?", "Weizen", "Hafer", "Gerste", "Hirse"),
  q("Essen & Trinken", 3, "Aus welchem Land stammt Paella?", "Spanien", "Portugal", "Mexiko", "Italien"),
  q("Essen & Trinken", 3, "Wie heißt das japanische Gericht aus rohem Fisch ohne Reis?", "Sashimi", "Sushi", "Maki", "Tempura"),
  q("Essen & Trinken", 3, "Welche Beere gibt Gin sein typisches Aroma?", "Die Wacholderbeere", "Die Holunderbeere", "Die Schlehe", "Die Hagebutte"),
  q("Essen & Trinken", 3, "Welche Käsesorte ist für ihre großen Löcher bekannt?", "Emmentaler", "Gouda", "Camembert", "Cheddar"),
  q("Essen & Trinken", 3, "Woraus wird Marzipan hauptsächlich gemacht?", "Aus Mandeln", "Aus Haselnüssen", "Aus Cashews", "Aus Pistazien"),
  q("Essen & Trinken", 3, "Welches Land ist die Heimat des Gerichts „Gulasch“?", "Ungarn", "Österreich", "Tschechien", "Polen"),

  /* ---------------- Natur & Tiere ---------------- */
  q("Natur & Tiere", 1, "Wie viele Beine hat eine Spinne?", "8", "6", "10", "4"),
  q("Natur & Tiere", 1, "Welches ist das größte Tier der Welt?", "Der Blauwal", "Der Afrikanische Elefant", "Der Weiße Hai", "Die Giraffe"),
  q("Natur & Tiere", 1, "Welches Landtier ist das schnellste?", "Der Gepard", "Der Löwe", "Das Pferd", "Die Antilope"),
  q("Natur & Tiere", 1, "Welches Tier hat den längsten Hals?", "Die Giraffe", "Das Kamel", "Der Strauß", "Das Lama"),
  q("Natur & Tiere", 1, "Welches Insekt produziert Honig?", "Die Biene", "Die Wespe", "Die Hummel", "Die Ameise"),
  q("Natur & Tiere", 1, "Welcher Baum trägt Eicheln?", "Die Eiche", "Die Buche", "Die Birke", "Die Kastanie"),
  q("Natur & Tiere", 1, "Welches Tier trägt seine Jungen in einem Beutel?", "Das Känguru", "Der Waschbär", "Das Faultier", "Der Otter"),
  q("Natur & Tiere", 1, "Was fressen Pandas fast ausschließlich?", "Bambus", "Fisch", "Gras", "Beeren"),
  q("Natur & Tiere", 2, "Wie viele Herzen hat ein Oktopus?", "3", "1", "2", "5"),
  q("Natur & Tiere", 2, "Welches Säugetier kann aktiv fliegen?", "Die Fledermaus", "Das Flughörnchen", "Der Kolibri", "Der Gleitbeutler"),
  q("Natur & Tiere", 2, "Welcher ist der größte Vogel der Welt?", "Der Strauß", "Der Emu", "Der Albatros", "Der Kondor"),
  q("Natur & Tiere", 2, "Wie heißt das Junge eines Pferdes?", "Fohlen", "Kalb", "Lamm", "Welpe"),
  q("Natur & Tiere", 2, "Welches Tier wird auch „Wüstenschiff“ genannt?", "Das Kamel", "Das Zebra", "Die Oryxantilope", "Der Esel"),
  q("Natur & Tiere", 2, "Wie viele Beine hat ein Insekt?", "6", "8", "4", "10"),
  q("Natur & Tiere", 2, "Welche Blume dreht ihre Blüte nach der Sonne?", "Die Sonnenblume", "Die Tulpe", "Die Rose", "Der Mohn"),
  q("Natur & Tiere", 3, "Wie lange dauert die Tragzeit eines Elefanten ungefähr?", "22 Monate", "12 Monate", "9 Monate", "30 Monate"),
  q("Natur & Tiere", 3, "Wie viele Arme hat ein Seestern typischerweise?", "5", "6", "4", "8"),
  q("Natur & Tiere", 3, "Welcher Vogel kann rückwärts fliegen?", "Der Kolibri", "Der Specht", "Die Schwalbe", "Der Falke"),
  q("Natur & Tiere", 3, "Welche ist die größte Katzenart der Welt?", "Der Tiger", "Der Löwe", "Der Jaguar", "Der Leopard"),
  q("Natur & Tiere", 3, "Wie viele Mägen bzw. Magenkammern hat eine Kuh?", "4", "2", "3", "1"),
  q("Natur & Tiere", 3, "Welcher ist der größte Fisch der Welt?", "Der Walhai", "Der Weiße Hai", "Der Blauwal", "Der Mondfisch"),
  q("Natur & Tiere", 3, "Welcher Nadelbaum verliert im Winter seine Nadeln?", "Die Lärche", "Die Fichte", "Die Kiefer", "Die Tanne"),
  q("Natur & Tiere", 3, "Welche Baumart wird am höchsten?", "Der Küstenmammutbaum", "Die Eiche", "Die Douglasie", "Der Eukalyptus"),
  q("Natur & Tiere", 3, "Wie alt können Riesenschildkröten werden?", "Über 100 Jahre", "Etwa 30 Jahre", "Etwa 50 Jahre", "Über 300 Jahre"),
  q("Natur & Tiere", 3, "Wie nennt man ein Tier, das sich nur von Pflanzen ernährt?", "Pflanzenfresser (Herbivore)", "Allesfresser (Omnivore)", "Fleischfresser (Karnivore)", "Aasfresser"),
  q("Natur & Tiere", 3, "Wie heißt die Wissenschaft von den Pflanzen?", "Botanik", "Zoologie", "Ökologie", "Geologie")
];

/* =========================================================
   Ja/Nein-Fragen
   ---------------------------------------------------------
   jn(kategorie, schwierigkeit, frage, istWahr)
   Es gibt nur zwei Antwortknöpfe – „Ja“ steht immer links.
   ========================================================= */
const jn = (k, s, f, wahr) => ({
  k, s, f,
  r: wahr ? 'Ja' : 'Nein',
  w: [wahr ? 'Nein' : 'Ja'],
  jn: true
});

window.FRAGEN.push(

  /* ---------------- Allgemeinwissen ---------------- */
  jn("Allgemeinwissen", 1, "Hat ein Schaltjahr 366 Tage?", true),
  jn("Allgemeinwissen", 1, "Ist die Zahl 1 eine Primzahl?", false),
  jn("Allgemeinwissen", 2, "Ist Grün eine der drei Grundfarben bei Bildschirmen (RGB)?", true),
  jn("Allgemeinwissen", 2, "Steht die Abkürzung „PS“ bei Autos für „Pferdestärke“?", true),
  jn("Allgemeinwissen", 2, "Sind ein Kilobyte in der klassischen Informatik 1024 Byte?", true),
  jn("Allgemeinwissen", 3, "Muss man in Deutschland seinen Personalausweis immer bei sich tragen?", false),

  /* ---------------- Geografie ---------------- */
  jn("Geografie", 1, "Liegt Ägypten auf zwei Kontinenten?", true),
  jn("Geografie", 2, "Hat die Schweiz einen eigenen Zugang zum Meer?", false),
  jn("Geografie", 2, "Liegt Istanbul sowohl in Europa als auch in Asien?", true),
  jn("Geografie", 2, "Ist Grönland flächenmäßig größer als Australien?", false),
  jn("Geografie", 3, "Ist Reykjavík die nördlichste Hauptstadt der Welt?", true),
  jn("Geografie", 3, "Liegt Rom weiter nördlich als New York?", true),

  /* ---------------- Geschichte ---------------- */
  jn("Geschichte", 1, "Wurde die Berliner Mauer von der DDR errichtet?", true),
  jn("Geschichte", 2, "War Julius Caesar römischer Kaiser?", false),
  jn("Geschichte", 2, "Dauerte der Hundertjährige Krieg genau 100 Jahre?", false),
  jn("Geschichte", 2, "Gab es die Wikinger schon vor Christi Geburt?", false),
  jn("Geschichte", 3, "Stammte Kleopatra aus einer griechischen Herrscherfamilie?", true),
  jn("Geschichte", 3, "Sank die Titanic auf ihrer allerersten Fahrt?", true),

  /* ---------------- Wissenschaft ---------------- */
  jn("Wissenschaft", 1, "Ist die Sonne ein Stern?", true),
  jn("Wissenschaft", 2, "Ist Glas ein Metall?", false),
  jn("Wissenschaft", 2, "Könnte man auf dem Mond eine Explosion hören?", false),
  jn("Wissenschaft", 2, "Ist Blut im Körper blau, solange es kein Sauerstoff berührt?", false),
  jn("Wissenschaft", 3, "Wiegt ein Kilogramm Federn genauso viel wie ein Kilogramm Blei?", true),
  jn("Wissenschaft", 3, "Gilt Pluto heute offiziell noch als Planet?", false),

  /* ---------------- Sport ---------------- */
  jn("Sport", 1, "Darf ein Torwart den Ball außerhalb des Strafraums mit der Hand aufnehmen?", false),
  jn("Sport", 2, "Bestehen olympische Goldmedaillen aus reinem Gold?", false),
  jn("Sport", 2, "Ist Schach eine olympische Disziplin?", false),
  jn("Sport", 2, "Endet ein Tennissatz immer nach genau sechs gewonnenen Spielen?", false),
  jn("Sport", 3, "Hat Deutschland die Fußball-Weltmeisterschaft schon viermal gewonnen?", true),
  jn("Sport", 3, "Dauert ein NBA-Basketballspiel regulär 48 Minuten?", true),

  /* ---------------- Musik ---------------- */
  jn("Musik", 1, "Hat eine Geige vier Saiten?", true),
  jn("Musik", 2, "War Mozart schon als Kind als Musiker berühmt?", true),
  jn("Musik", 2, "Ist ein Cello größer als eine Bratsche?", true),
  jn("Musik", 3, "War Beethoven gegen Ende seines Lebens taub?", true),
  jn("Musik", 3, "Sind die Beatles früher regelmäßig in Hamburg aufgetreten?", true),
  jn("Musik", 3, "Hat ABBA den Eurovision Song Contest gewonnen?", true),

  /* ---------------- Film & TV ---------------- */
  jn("Film & TV", 1, "Ist „Shrek“ ein Disney-Film?", false),
  jn("Film & TV", 2, "Gewann „Der Herr der Ringe: Die Rückkehr des Königs“ den Oscar als bester Film?", true),
  jn("Film & TV", 2, "Spricht Chewbacca in „Star Wars“ Englisch?", false),
  jn("Film & TV", 3, "Sind „Die Simpsons“ die am längsten laufende US-Zeichentrickserie zur Hauptsendezeit?", true),
  jn("Film & TV", 3, "Stammt der Film „Das Boot“ aus Deutschland?", true),
  jn("Film & TV", 3, "Spielte Arnold Schwarzenegger im ersten „Terminator“ den Bösewicht?", true),

  /* ---------------- Gaming & Internet ---------------- */
  jn("Gaming & Internet", 1, "Kann man in Minecraft im Kreativmodus fliegen?", true),
  jn("Gaming & Internet", 2, "Gehört Instagram zu Google?", false),
  jn("Gaming & Internet", 2, "War Mario in seinem allerersten Spiel Zimmermann statt Klempner?", true),
  jn("Gaming & Internet", 2, "Kostet Fortnite beim Herunterladen Geld?", false),
  jn("Gaming & Internet", 3, "Steht „WWW“ für „World Wide Web“?", true),
  jn("Gaming & Internet", 3, "War die Xbox Microsofts erste eigene Spielkonsole?", true),

  /* ---------------- Essen & Trinken ---------------- */
  jn("Essen & Trinken", 1, "Sind Erdnüsse botanisch gesehen Nüsse?", false),
  jn("Essen & Trinken", 2, "Enthält weiße Schokolade Kakaomasse?", false),
  jn("Essen & Trinken", 2, "Wächst Wasabi ursprünglich in Japan?", true),
  jn("Essen & Trinken", 2, "Sind Tomaten botanisch gesehen Früchte?", true),
  jn("Essen & Trinken", 3, "Stammt Ketchup ursprünglich aus den USA?", false),
  jn("Essen & Trinken", 3, "Ist in alkoholfreiem Bier wirklich null Alkohol enthalten?", false),

  /* ---------------- Natur & Tiere ---------------- */
  jn("Natur & Tiere", 1, "Sind Fledermäuse Vögel?", false),
  jn("Natur & Tiere", 1, "Können Pinguine fliegen?", false),
  jn("Natur & Tiere", 2, "Sind Delfine Fische?", false),
  jn("Natur & Tiere", 2, "Haben Schnecken Zähne?", true),
  jn("Natur & Tiere", 3, "Können Kamele wochenlang ohne Wasser auskommen?", true),
  jn("Natur & Tiere", 3, "Ist der Koala ein Bär?", false)
);

/* =========================================================
   Nachschub – weitere Fragen
   ========================================================= */
window.FRAGEN.push(

  /* ---------------- Allgemeinwissen ---------------- */
  q("Allgemeinwissen", 1, "Welche Farbe leuchtet bei einer Ampel ganz oben?", "Rot", "Gelb", "Grün", "Orange"),
  q("Allgemeinwissen", 1, "Wie viele Tage hat der Februar in einem Schaltjahr?", "29", "28", "30", "31"),
  q("Allgemeinwissen", 1, "Wie viele Karten hat ein französisches Blatt ohne Joker?", "52", "32", "48", "56"),
  q("Allgemeinwissen", 1, "Mit wie vielen Figuren startet ein Spieler beim Schach?", "16", "12", "18", "20"),
  q("Allgemeinwissen", 1, "Welche Zahl schreibt man römisch als „X“?", "10", "5", "50", "100"),
  q("Allgemeinwissen", 1, "Wie viele Grad ergibt die Innenwinkelsumme eines Dreiecks?", "180", "90", "270", "360"),
  q("Allgemeinwissen", 1, "Welche Schulnote ist in Deutschland die beste?", "Die 1", "Die 6", "Die 10", "Die 0"),
  q("Allgemeinwissen", 1, "Wie viele Kanten hat ein Würfel?", "12", "8", "6", "16"),
  q("Allgemeinwissen", 2, "Wie viele Bundesländer Deutschlands sind Stadtstaaten?", "3", "2", "4", "1"),
  q("Allgemeinwissen", 2, "Wofür steht die Abkürzung „DIY“?", "Do it yourself", "Done in a year", "Design it yourself", "Do it young"),
  q("Allgemeinwissen", 2, "Wie viele Nullen hat eine Milliarde?", "9", "6", "12", "10"),
  q("Allgemeinwissen", 2, "Wie viele Minuten hat ein ganzer Tag?", "1.440", "960", "2.400", "720"),
  q("Allgemeinwissen", 2, "Wofür steht die Abkürzung „e. V.“?", "Eingetragener Verein", "Ehrenamtliche Vereinigung", "Einfacher Verband", "Europäischer Verein"),
  q("Allgemeinwissen", 2, "Wie viele Sterne hat die Flagge Chinas?", "5", "1", "7", "3"),
  q("Allgemeinwissen", 2, "Wie nennt man den 29. Februar?", "Schalttag", "Springtag", "Zusatztag", "Kalendertag"),
  q("Allgemeinwissen", 2, "Welche Farbe hat das Feld mit der Null beim Roulette?", "Grün", "Rot", "Schwarz", "Blau"),
  q("Allgemeinwissen", 2, "Wie viele Einwohner hat Deutschland ungefähr?", "83 Millionen", "65 Millionen", "95 Millionen", "110 Millionen"),
  q("Allgemeinwissen", 2, "Welche Farbe haben die Pannenfahrzeuge des ADAC?", "Gelb", "Orange", "Rot", "Weiß"),
  q("Allgemeinwissen", 3, "Wofür steht die Abkürzung „IBAN“?", "International Bank Account Number", "Internationale Bankanweisungsnummer", "Interne Bankauskunftsnummer", "International Banking Access Node"),
  q("Allgemeinwissen", 3, "Aus wie vielen Zeilen besteht ein Sonett?", "14", "12", "16", "10"),
  q("Allgemeinwissen", 3, "Was ist ein Oxymoron?", "Die Verbindung zweier sich widersprechender Begriffe", "Ein Wort mit doppelter Bedeutung", "Eine bewusste Übertreibung", "Ein erfundenes Wort"),
  q("Allgemeinwissen", 3, "Wie viele ständige Mitglieder hat der UN-Sicherheitsrat?", "5", "7", "10", "15"),
  q("Allgemeinwissen", 3, "Wofür steht die Dateiendung „PDF“?", "Portable Document Format", "Printed Data File", "Personal Document Folder", "Public Document Format"),
  q("Allgemeinwissen", 3, "Welche ist die kleinste dreistellige Primzahl?", "101", "100", "103", "111"),
  q("Allgemeinwissen", 3, "Wie viele Durchgänge hat das Brandenburger Tor?", "5", "3", "7", "1"),

  /* ---------------- Geografie ---------------- */
  q("Geografie", 1, "Wie heißt die Hauptstadt von Spanien?", "Madrid", "Barcelona", "Valencia", "Sevilla"),
  q("Geografie", 1, "In welchem Land steht der Schiefe Turm von Pisa?", "Italien", "Spanien", "Griechenland", "Portugal"),
  q("Geografie", 1, "Welcher Kontinent ist der kälteste?", "Die Antarktis", "Europa", "Nordamerika", "Asien"),
  q("Geografie", 1, "Wie heißt der größte Fluss Südamerikas?", "Der Amazonas", "Der Orinoco", "Der Paraná", "Der Rio Grande"),
  q("Geografie", 1, "Welche Farbe hat der Kreis in der Mitte der japanischen Flagge?", "Rot", "Blau", "Gold", "Schwarz"),
  q("Geografie", 1, "Wie heißt die größte Insel der Welt?", "Grönland", "Australien", "Madagaskar", "Borneo"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Norwegen?", "Oslo", "Bergen", "Stockholm", "Kopenhagen"),
  q("Geografie", 2, "Welches Gebirge gilt als Grenze zwischen Europa und Asien?", "Der Ural", "Der Kaukasus", "Die Karpaten", "Der Altai"),
  q("Geografie", 2, "In welchem Bundesland liegt der Schwarzwald?", "Baden-Württemberg", "Bayern", "Hessen", "Rheinland-Pfalz"),
  q("Geografie", 2, "Welches Land ist flächenmäßig das größte der Welt?", "Russland", "Kanada", "China", "USA"),
  q("Geografie", 2, "In welcher deutschen Stadt liegt der größte Seehafen des Landes?", "Hamburg", "Bremen", "Rostock", "Kiel"),
  q("Geografie", 2, "In welchem Land liegt Machu Picchu?", "Peru", "Mexiko", "Bolivien", "Chile"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Portugal?", "Lissabon", "Porto", "Madrid", "Faro"),
  q("Geografie", 2, "Welcher Berg ist der höchste Afrikas?", "Der Kilimandscharo", "Der Kenia", "Der Atlas", "Der Tafelberg"),
  q("Geografie", 2, "An welches Meer grenzt Polen im Norden?", "An die Ostsee", "An die Nordsee", "An das Schwarze Meer", "An das Kaspische Meer"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Marokko?", "Rabat", "Casablanca", "Marrakesch", "Fès"),
  q("Geografie", 3, "Welcher Fluss fließt durch Kairo?", "Der Nil", "Der Euphrat", "Der Jordan", "Der Kongo"),
  q("Geografie", 3, "Wie heißt die tiefste bekannte Stelle der Ozeane?", "Der Marianengraben", "Der Japangraben", "Der Puerto-Rico-Graben", "Der Sundagraben"),
  q("Geografie", 3, "Welcher Staat ist vollständig von Italien umgeben – außer dem Vatikan?", "San Marino", "Monaco", "Andorra", "Malta"),
  q("Geografie", 3, "In welchem Bundesland liegt die Insel Rügen?", "Mecklenburg-Vorpommern", "Schleswig-Holstein", "Niedersachsen", "Brandenburg"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Vietnam?", "Hanoi", "Ho-Chi-Minh-Stadt", "Bangkok", "Phnom Penh"),
  q("Geografie", 3, "Welcher Kanal verbindet das Mittelmeer mit dem Roten Meer?", "Der Suezkanal", "Der Panamakanal", "Der Kieler Kanal", "Der Bosporus"),
  q("Geografie", 3, "Nairobi ist die Hauptstadt welches Landes?", "Kenia", "Tansania", "Uganda", "Äthiopien"),
  q("Geografie", 3, "Welcher Fluss bildet einen großen Teil der Grenze zwischen den USA und Mexiko?", "Der Rio Grande", "Der Colorado", "Der Mississippi", "Der Missouri"),
  q("Geografie", 3, "Wie heißt der größte See Afrikas?", "Der Viktoriasee", "Der Tanganjikasee", "Der Malawisee", "Der Tschadsee")
);

window.FRAGEN.push(

  /* ---------------- Geschichte ---------------- */
  q("Geschichte", 1, "In welchem Jahr endete der Zweite Weltkrieg in Europa?", "1945", "1944", "1946", "1943"),
  q("Geschichte", 1, "Welches Volk erbaute die Pyramiden von Gizeh?", "Die Ägypter", "Die Römer", "Die Griechen", "Die Perser"),
  q("Geschichte", 1, "Wodurch wurde Anne Frank weltbekannt?", "Durch ihr Tagebuch aus dem Versteck", "Durch ein Gemälde", "Durch eine Radiosendung", "Durch eine Erfindung"),
  q("Geschichte", 2, "Wie hieß das Schiff, mit dem die Pilgerväter 1620 nach Amerika segelten?", "Mayflower", "Santa Maria", "Endeavour", "Beagle"),
  q("Geschichte", 2, "Welcher Erfinder gründete General Electric und machte die Glühlampe marktreif?", "Thomas Edison", "Nikola Tesla", "Werner von Siemens", "Alexander Graham Bell"),
  q("Geschichte", 2, "Wer war der berühmteste Herrscher der Mongolen?", "Dschingis Khan", "Attila", "Timur", "Kublai Khan"),
  q("Geschichte", 2, "In welchem Land begann die Industrielle Revolution?", "In Großbritannien", "In Deutschland", "In Frankreich", "In den USA"),
  q("Geschichte", 2, "Wer hielt die Rede „I have a dream“?", "Martin Luther King", "Malcolm X", "Nelson Mandela", "Barack Obama"),
  q("Geschichte", 2, "In welchem Jahr wurde John F. Kennedy erschossen?", "1963", "1961", "1965", "1968"),
  q("Geschichte", 2, "Wer war der erste Mensch im Weltall?", "Juri Gagarin", "Neil Armstrong", "Alan Shepard", "German Titow"),
  q("Geschichte", 2, "Welche Seuche tötete im 14. Jahrhundert Millionen Europäer?", "Die Pest", "Die Cholera", "Die Pocken", "Die Grippe"),
  q("Geschichte", 2, "Welche Stadt war die Hauptstadt des Byzantinischen Reiches?", "Konstantinopel", "Athen", "Rom", "Damaskus"),
  q("Geschichte", 3, "Welcher Vertrag beendete 1919 offiziell den Ersten Weltkrieg?", "Der Versailler Vertrag", "Der Vertrag von Trianon", "Der Westfälische Friede", "Der Wiener Kongress"),
  q("Geschichte", 3, "Wer war die erste Frau, die einen Nobelpreis erhielt?", "Marie Curie", "Lise Meitner", "Rosalind Franklin", "Ada Lovelace"),
  q("Geschichte", 3, "Welches Reich beherrschte vor den Spaniern die Anden Südamerikas?", "Das Inkareich", "Das Aztekenreich", "Das Mayareich", "Das Olmekenreich"),
  q("Geschichte", 3, "Wann trat der Vertrag von Maastricht in Kraft, mit dem die EU entstand?", "1993", "1989", "1997", "2002"),
  q("Geschichte", 3, "Wer erhielt 1876 das Patent auf das Telefon?", "Alexander Graham Bell", "Thomas Edison", "Guglielmo Marconi", "Samuel Morse"),
  q("Geschichte", 3, "Wie hieß die erste Frau im Weltall?", "Walentina Tereschkowa", "Sally Ride", "Swetlana Sawizkaja", "Mae Jemison"),
  q("Geschichte", 3, "Welcher Herrscher wurde im Jahr 800 in Rom zum Kaiser gekrönt?", "Karl der Große", "Otto I.", "Friedrich Barbarossa", "Heinrich IV."),
  q("Geschichte", 3, "Wie nennt man die deutsche Staatsform zwischen 1918 und 1933?", "Weimarer Republik", "Deutsches Kaiserreich", "Norddeutscher Bund", "Deutscher Bund"),
  q("Geschichte", 3, "In welchem Jahr ging das Weströmische Reich unter?", "476 n. Chr.", "395 n. Chr.", "410 n. Chr.", "527 n. Chr."),
  q("Geschichte", 3, "Wessen Expedition umsegelte als erste die Welt?", "Die von Ferdinand Magellan", "Die von Vasco da Gama", "Die von James Cook", "Die von Francis Drake"),
  q("Geschichte", 3, "Wer war Sitting Bull?", "Ein Häuptling der Lakota-Sioux", "Ein US-General", "Ein Goldgräber", "Ein Präsident"),
  q("Geschichte", 3, "Welches Land kaufte 1867 Alaska von Russland?", "Die USA", "Kanada", "Großbritannien", "Dänemark"),
  q("Geschichte", 3, "Wie hieß der letzte Zar Russlands?", "Nikolaus II.", "Alexander III.", "Peter III.", "Iwan IV."),

  /* ---------------- Wissenschaft ---------------- */
  q("Wissenschaft", 1, "Welches Organ pumpt das Blut durch den Körper?", "Das Herz", "Die Lunge", "Die Leber", "Die Niere"),
  q("Wissenschaft", 1, "Wie heißt der natürliche Trabant der Erde?", "Der Mond", "Die Venus", "Phobos", "Titan"),
  q("Wissenschaft", 1, "Bei wie viel Grad Celsius gefriert Wasser?", "0", "-10", "4", "10"),
  q("Wissenschaft", 1, "Welches Gas brauchen Menschen zum Atmen?", "Sauerstoff", "Stickstoff", "Kohlendioxid", "Helium"),
  q("Wissenschaft", 1, "Wie viel Grad Celsius hat der menschliche Körper normalerweise?", "Rund 37", "Rund 34", "Rund 40", "Rund 30"),
  q("Wissenschaft", 2, "Welches chemische Symbol steht für Eisen?", "Fe", "Ei", "Ir", "Fr"),
  q("Wissenschaft", 2, "Wie heißt die Kraft, die uns auf dem Boden hält?", "Die Schwerkraft", "Die Fliehkraft", "Die Reibung", "Der Magnetismus"),
  q("Wissenschaft", 2, "Wie viele Aggregatzustände von Wasser kennt man im Alltag?", "3", "2", "4", "5"),
  q("Wissenschaft", 2, "Welches Organ produziert Insulin?", "Die Bauchspeicheldrüse", "Die Leber", "Die Milz", "Die Schilddrüse"),
  q("Wissenschaft", 2, "Wie nennt man Tiere mit einer Wirbelsäule?", "Wirbeltiere", "Weichtiere", "Gliederfüßer", "Nesseltiere"),
  q("Wissenschaft", 2, "Welche Einheit misst die elektrische Stromstärke?", "Ampere", "Volt", "Watt", "Ohm"),
  q("Wissenschaft", 2, "Wie nennt man den Übergang von flüssig zu gasförmig?", "Verdampfen", "Schmelzen", "Kondensieren", "Erstarren"),
  q("Wissenschaft", 2, "Wofür steht „RAM“ beim Computer?", "Random Access Memory", "Read And Modify", "Rapid Access Module", "Runtime Allocation Memory"),
  q("Wissenschaft", 3, "Welches Element hat das Symbol „K“?", "Kalium", "Kohlenstoff", "Krypton", "Kupfer"),
  q("Wissenschaft", 3, "Wie lange braucht das Sonnenlicht bis zur Erde?", "Etwa 8 Minuten", "Etwa 8 Sekunden", "Etwa 1 Stunde", "Etwa 1 Sekunde"),
  q("Wissenschaft", 3, "Wer formulierte die drei Bewegungsgesetze der Mechanik?", "Isaac Newton", "Galileo Galilei", "Johannes Kepler", "Blaise Pascal"),
  q("Wissenschaft", 3, "Was ist ein Isotop?", "Ein Atom mit gleicher Protonen-, aber anderer Neutronenzahl", "Ein geladenes Atom", "Ein Molekül aus zwei Atomen", "Ein instabiles Molekül"),
  q("Wissenschaft", 3, "Welches natürliche Material ist am härtesten?", "Diamant", "Quarz", "Stahl", "Granit"),
  q("Wissenschaft", 3, "Wie heißt die kleinste lebende Einheit eines Organismus?", "Die Zelle", "Das Atom", "Das Gen", "Das Organ"),
  q("Wissenschaft", 3, "Womit beschäftigt sich die Ornithologie?", "Mit Vögeln", "Mit Insekten", "Mit Fischen", "Mit Pflanzen"),
  q("Wissenschaft", 3, "Wer entdeckte die nach ihm benannten Röntgenstrahlen?", "Wilhelm Conrad Röntgen", "Marie Curie", "Max Planck", "Otto Hahn"),
  q("Wissenschaft", 3, "Wie viele chemische Elemente kennt das Periodensystem heute?", "118", "92", "104", "150"),
  q("Wissenschaft", 3, "Welchen pH-Wert hat reines Wasser?", "7", "0", "10", "14"),
  q("Wissenschaft", 3, "Wie nennt man den direkten Übergang von fest zu gasförmig?", "Sublimation", "Kondensation", "Diffusion", "Fusion"),
  q("Wissenschaft", 3, "Was misst ein Seismograf?", "Erdbebenwellen", "Die Luftfeuchtigkeit", "Die Sonnenstrahlung", "Den Salzgehalt")
);

window.FRAGEN.push(

  /* ---------------- Sport ---------------- */
  q("Sport", 1, "Womit dürfen Feldspieler im Fußball den Ball nicht spielen?", "Mit den Händen", "Mit dem Kopf", "Mit der Brust", "Mit dem Oberschenkel"),
  q("Sport", 1, "Wie viele Punkte zählt ein normaler Korbwurf im Basketball?", "2", "1", "3", "4"),
  q("Sport", 1, "In welcher Sportart gibt es „Strike“ und „Spare“?", "Bowling", "Baseball", "Darts", "Golf"),
  q("Sport", 1, "Welche Sportart spielt man mit Schläger und Federball?", "Badminton", "Squash", "Tennis", "Tischtennis"),
  q("Sport", 2, "Wie viele Spieler einer Eishockeymannschaft stehen auf dem Eis?", "6", "5", "7", "8"),
  q("Sport", 2, "In welchem Stadion spielt der FC Barcelona?", "Im Camp Nou", "Im Bernabéu", "Im Wanda Metropolitano", "Im San Siro"),
  q("Sport", 2, "Alle wie viele Jahre findet die Fußball-Europameisterschaft statt?", "Alle 4 Jahre", "Alle 2 Jahre", "Alle 3 Jahre", "Alle 5 Jahre"),
  q("Sport", 2, "In welcher Sportart spricht man von einem „Ass“?", "Tennis", "Fußball", "Handball", "Turnen"),
  q("Sport", 2, "Was droht Biathletinnen und Biathleten meist nach einem Fehlschuss?", "Eine Strafrunde", "Eine Zeitgutschrift", "Ein Punktabzug", "Der Ausschluss"),
  q("Sport", 2, "Wie lang ist ein olympisches Schwimmbecken?", "50 Meter", "25 Meter", "100 Meter", "75 Meter"),
  q("Sport", 2, "Welche Nation dominiert traditionell das Tischtennis?", "China", "Japan", "Schweden", "Südkorea"),
  q("Sport", 2, "Wie heißt das Endspiel der National Football League?", "Super Bowl", "World Series", "Stanley Cup", "Final Four"),
  q("Sport", 2, "In welcher Sportart wurde Dirk Nowitzki weltberühmt?", "Basketball", "Handball", "Volleyball", "Tennis"),
  q("Sport", 3, "Wie viele Punkte bringt ein Field Goal im American Football?", "3", "2", "6", "1"),
  q("Sport", 3, "Zu welcher Disziplin gehört der „Fosbury Flop“?", "Hochsprung", "Weitsprung", "Stabhochsprung", "Turmspringen"),
  q("Sport", 3, "Wie viele Formel-1-Weltmeistertitel hat Lewis Hamilton geholt?", "7", "5", "6", "8"),
  q("Sport", 3, "Wie schwer ist die Kugel beim Kugelstoßen der Männer?", "7,26 kg", "5 kg", "10 kg", "4 kg"),
  q("Sport", 3, "Wie viele Sätze werden beim Volleyball maximal gespielt?", "5", "3", "4", "7"),
  q("Sport", 3, "In welcher Stadt fanden 1896 die ersten modernen Olympischen Spiele statt?", "Athen", "Paris", "Rom", "London"),
  q("Sport", 3, "Wie heißt der Weltfußballverband?", "FIFA", "UEFA", "IOC", "DFB"),
  q("Sport", 3, "Wofür steht „K. o.“ im Boxen?", "Knockout", "Kampf ohne Wertung", "Konterschlag", "Klare Überlegenheit"),
  q("Sport", 3, "Wie lang ist eine Runde auf einer Standard-Laufbahn im Stadion?", "400 Meter", "300 Meter", "500 Meter", "250 Meter"),
  q("Sport", 3, "Wie viele Spieler hat eine Rugby-Union-Mannschaft auf dem Feld?", "15", "11", "13", "7"),
  q("Sport", 3, "Wie viele Löcher hat eine kurze „Neun-Loch-Runde“ beim Golf?", "9", "12", "6", "18"),
  q("Sport", 3, "Welche Sportart wird auf einem „Tatami“ ausgeübt?", "Judo", "Fechten", "Boxen", "Ringen"),

  /* ---------------- Musik ---------------- */
  q("Musik", 1, "Wie viele Saiten hat ein E-Bass üblicherweise?", "4", "6", "5", "8"),
  q("Musik", 1, "Welches Instrument spielt man mit einem Bogen?", "Die Geige", "Die Trompete", "Die Flöte", "Das Klavier"),
  q("Musik", 1, "Wie heißt die höchste Frauenstimmlage?", "Sopran", "Alt", "Tenor", "Bass"),
  q("Musik", 2, "Welche Band veröffentlichte „Highway to Hell“?", "AC/DC", "Metallica", "Guns N’ Roses", "Iron Maiden"),
  q("Musik", 2, "Wer sang „Shape of You“?", "Ed Sheeran", "Justin Bieber", "Sam Smith", "Harry Styles"),
  q("Musik", 2, "Welche schwedische Band sang „Dancing Queen“?", "ABBA", "Roxette", "Ace of Base", "A-ha"),
  q("Musik", 2, "Welches Instrument spielte Jimi Hendrix?", "Die Gitarre", "Das Schlagzeug", "Das Saxofon", "Die Orgel"),
  q("Musik", 2, "Wie heißt die tiefste Männerstimmlage?", "Bass", "Tenor", "Bariton", "Alt"),
  q("Musik", 2, "Wer singt „Atemlos durch die Nacht“?", "Helene Fischer", "Andrea Berg", "Vanessa Mai", "Michelle"),
  q("Musik", 2, "Welche Musikrichtung entstand in Jamaika?", "Reggae", "Samba", "Blues", "Flamenco"),
  q("Musik", 2, "Welches Instrument hat Pedale und rund 47 Saiten?", "Die Harfe", "Das Cembalo", "Die Zither", "Der Kontrabass"),
  q("Musik", 3, "Wie viele Sinfonien vollendete Beethoven?", "9", "7", "12", "5"),
  q("Musik", 3, "Welche Band veröffentlichte „The Dark Side of the Moon“?", "Pink Floyd", "The Doors", "Genesis", "Yes"),
  q("Musik", 3, "Was bedeutet die Vortragsbezeichnung „piano“?", "Leise", "Laut", "Schneller werdend", "Getragen"),
  q("Musik", 3, "In welcher Stadt wurde Mozart geboren?", "Salzburg", "Wien", "Prag", "München"),
  q("Musik", 3, "Wer komponierte den Opernzyklus „Der Ring des Nibelungen“?", "Richard Wagner", "Richard Strauss", "Giuseppe Verdi", "Gustav Mahler"),
  q("Musik", 3, "Wie viele Linien hat ein Notensystem?", "5", "4", "6", "7"),
  q("Musik", 3, "Welcher Sänger wurde als „The King“ bekannt?", "Elvis Presley", "Frank Sinatra", "Johnny Cash", "Chuck Berry"),
  q("Musik", 3, "Aus welchem Land stammt die Band U2?", "Irland", "England", "Schottland", "Australien"),
  q("Musik", 3, "Welches Instrument spielt man mit Schlägeln auf Holzstäben?", "Das Xylofon", "Das Akkordeon", "Die Pauke", "Das Vibrafon"),
  q("Musik", 3, "Wer komponierte die „Brandenburgischen Konzerte“?", "Johann Sebastian Bach", "Georg Friedrich Händel", "Joseph Haydn", "Georg Philipp Telemann"),
  q("Musik", 3, "Was ist ein „Riff“ in der Rockmusik?", "Eine kurze, ständig wiederholte Tonfolge", "Ein Trommelwirbel", "Ein Gesangssolo", "Ein Verstärkereffekt"),
  q("Musik", 3, "Wer sang „I Will Always Love You“ im Film „Bodyguard“?", "Whitney Houston", "Mariah Carey", "Tina Turner", "Céline Dion"),
  q("Musik", 3, "Wer komponierte den berühmten Hochzeitsmarsch aus „Ein Sommernachtstraum“?", "Felix Mendelssohn Bartholdy", "Richard Wagner", "Frédéric Chopin", "Franz Liszt"),
  q("Musik", 3, "Welches Instrument gehört klassischerweise nicht in ein Streichquartett?", "Die Flöte", "Die Geige", "Die Bratsche", "Das Cello")
);

window.FRAGEN.push(

  /* ---------------- Film & TV ---------------- */
  q("Film & TV", 1, "Welches Märchen handelt von einer Prinzessin, die sich an einem Spinnrad sticht?", "Dornröschen", "Aschenputtel", "Schneewittchen", "Rapunzel"),
  q("Film & TV", 1, "Welche Farbe hat Hulk?", "Grün", "Blau", "Rot", "Grau"),
  q("Film & TV", 1, "Wie heißt die berühmteste Maus von Disney?", "Micky Maus", "Minnie Maus", "Jerry", "Speedy Gonzales"),
  q("Film & TV", 2, "In welchem Film sucht ein Mädchen namens Dorothy einen Zauberer?", "Der Zauberer von Oz", "Alice im Wunderland", "Die Brücke nach Terabithia", "Peter Pan"),
  q("Film & TV", 2, "Wie heißt Batmans Butler?", "Alfred", "Jarvis", "Lucius", "Gordon"),
  q("Film & TV", 2, "Welcher Schauspieler spielte Forrest Gump?", "Tom Hanks", "Kevin Costner", "Bill Murray", "Robin Williams"),
  q("Film & TV", 2, "In welcher Serie arbeiten die Hauptfiguren im Seattle Grace Hospital?", "Grey’s Anatomy", "Emergency Room", "House", "Chicago Med"),
  q("Film & TV", 2, "Wie heißt der Schulleiter von Hogwarts in den ersten Harry-Potter-Filmen?", "Albus Dumbledore", "Severus Snape", "Rubeus Hagrid", "Remus Lupin"),
  q("Film & TV", 2, "Welcher Schauspieler verkörpert Indiana Jones?", "Harrison Ford", "Mel Gibson", "Kurt Russell", "Michael Douglas"),
  q("Film & TV", 2, "Welche Serie spielt in der Werbebranche im New York der 1960er?", "Mad Men", "Suits", "The Office", "Boardwalk Empire"),
  q("Film & TV", 3, "Wer spielte Hannibal Lecter in „Das Schweigen der Lämmer“?", "Anthony Hopkins", "Al Pacino", "Jack Nicholson", "Gary Oldman"),
  q("Film & TV", 3, "In welchem Jahr kam der erste „Star Wars“-Film ins Kino?", "1977", "1980", "1972", "1983"),
  q("Film & TV", 3, "Welche Familie steht im Mittelpunkt von „Der Pate“?", "Die Corleones", "Die Sopranos", "Die Barzinis", "Die Gambinos"),
  q("Film & TV", 3, "Wie heißt die deutsche Krimireihe, die seit 1970 sonntagabends läuft?", "Tatort", "Polizeiruf 110", "Der Alte", "SOKO"),
  q("Film & TV", 3, "Welcher Regisseur drehte „Pulp Fiction“?", "Quentin Tarantino", "Martin Scorsese", "Robert Rodriguez", "Coen-Brüder"),
  q("Film & TV", 3, "In welchem Animationsfilm verliebt sich ein Müllroboter?", "WALL·E", "Robots", "Big Hero 6", "Der Gigant aus dem All"),
  q("Film & TV", 3, "Wer spielte als Erster James Bond im Kino?", "Sean Connery", "Roger Moore", "George Lazenby", "Timothy Dalton"),
  q("Film & TV", 3, "Welche Serie erzählt vom kolumbianischen Drogenkartell um Pablo Escobar?", "Narcos", "Ozark", "El Chapo", "Queen of the South"),
  q("Film & TV", 3, "Welche Zeichentrickserie spielt in einer Kleinstadt in Colorado?", "South Park", "Family Guy", "Rick and Morty", "Futurama"),
  q("Film & TV", 3, "Auf welchem Wüstenplaneten spielt „Dune“?", "Arrakis", "Tatooine", "Vulcan", "Caladan"),
  q("Film & TV", 3, "Wie viele Staffeln hat „Breaking Bad“?", "5", "4", "6", "7"),
  q("Film & TV", 3, "In welchem Königreich spielt „Die Eiskönigin“?", "Arendelle", "Corona", "Atlantica", "Zaubertal"),
  q("Film & TV", 3, "Welcher Zeichentrickfilm war der erste abendfüllende Disney-Film?", "Schneewittchen und die sieben Zwerge", "Bambi", "Pinocchio", "Fantasia"),
  q("Film & TV", 3, "Welcher Schauspieler spielt Jack Sparrow?", "Johnny Depp", "Orlando Bloom", "Geoffrey Rush", "Javier Bardem"),
  q("Film & TV", 3, "Wie heißt der Superschurke mit dem lila Handschuh im Marvel-Universum?", "Thanos", "Loki", "Ultron", "Killmonger"),

  /* ---------------- Gaming & Internet ---------------- */
  q("Gaming & Internet", 1, "Welche gelbe Figur frisst im Labyrinth Punkte?", "Pac-Man", "Sonic", "Kirby", "Q*bert"),
  q("Gaming & Internet", 1, "Wie heißt Marios Bruder?", "Luigi", "Wario", "Yoshi", "Toad"),
  q("Gaming & Internet", 1, "Auf welcher Plattform teilt man kurze Videos mit Musik?", "TikTok", "LinkedIn", "Pinterest", "Reddit"),
  q("Gaming & Internet", 2, "Welches Studio entwickelt „Grand Theft Auto“?", "Rockstar Games", "Ubisoft", "EA", "Bethesda"),
  q("Gaming & Internet", 2, "Wie heißt der Held der „Zelda“-Spiele?", "Link", "Zelda", "Ganon", "Navi"),
  q("Gaming & Internet", 2, "Welche Konsole folgte auf die PlayStation 4?", "Die PlayStation 5", "Die PlayStation Pro", "Die Xbox Series X", "Die PS Vita"),
  q("Gaming & Internet", 2, "Wofür steht das Genrekürzel „FPS“?", "First Person Shooter", "Fast Paced Sports", "Free Play Story", "Full Party System"),
  q("Gaming & Internet", 2, "Welches Unternehmen entwickelt Windows?", "Microsoft", "Apple", "IBM", "Oracle"),
  q("Gaming & Internet", 2, "Wer gilt als Erfinder des World Wide Web?", "Tim Berners-Lee", "Bill Gates", "Steve Wozniak", "Vint Cerf"),
  q("Gaming & Internet", 2, "Welche Plattform besteht aus nutzererstellten Spielen mit Klötzchen-Figuren?", "Roblox", "Minecraft", "Fortnite", "Rec Room"),
  q("Gaming & Internet", 2, "Welche Suchmaschine wird weltweit am häufigsten genutzt?", "Google", "Bing", "DuckDuckGo", "Yahoo"),
  q("Gaming & Internet", 2, "Welches soziale Netzwerk hieß früher Twitter?", "X", "Threads", "Bluesky", "Mastodon"),
  q("Gaming & Internet", 3, "Wofür steht das Genrekürzel „RPG“?", "Rollenspiel", "Rennspiel", "Rätselspiel", "Rundenstrategie"),
  q("Gaming & Internet", 3, "Welche Firma entwickelte „Counter-Strike“?", "Valve", "Riot Games", "Blizzard", "Capcom"),
  q("Gaming & Internet", 3, "Was ist ein „Buff“ in Videospielen?", "Eine Verstärkung einer Fähigkeit", "Ein Spielfehler", "Ein Endgegner", "Ein Ladebildschirm"),
  q("Gaming & Internet", 3, "Wie heißt Valves Online-Shop für PC-Spiele?", "Steam", "Origin", "Epic Store", "GOG"),
  q("Gaming & Internet", 3, "Welches Studio entwickelte Minecraft ursprünglich?", "Mojang", "Notch Interactive", "Rockstar", "Telltale"),
  q("Gaming & Internet", 3, "Was macht ein Emulator?", "Er ahmt fremde Hardware auf einem Gerät nach", "Er beschleunigt das Internet", "Er speichert Spielstände online", "Er blockiert Werbung"),
  q("Gaming & Internet", 3, "Wie hieß das erste kommerziell erfolgreiche Videospiel von 1972?", "Pong", "Space Invaders", "Asteroids", "Computer Space"),
  q("Gaming & Internet", 3, "Welche Spielkonsole verkaufte sich weltweit am häufigsten?", "Die PlayStation 2", "Die Nintendo Wii", "Die Xbox 360", "Der Game Boy"),
  q("Gaming & Internet", 3, "Wofür steht „HTML“?", "Hypertext Markup Language", "High Tech Media Language", "Home Tool Markup Language", "Hyperlink Text Machine Language"),
  q("Gaming & Internet", 3, "Welches Unternehmen kaufte 2014 den Minecraft-Entwickler?", "Microsoft", "Sony", "Google", "Tencent"),
  q("Gaming & Internet", 3, "Was ist ein „Bot“ im Internet?", "Ein automatisch handelndes Programm", "Ein gehackter Zugang", "Ein Serverfehler", "Ein Werbebanner"),
  q("Gaming & Internet", 3, "Wofür steht „DLC“ bei Videospielen?", "Downloadable Content", "Direct Level Creator", "Digital License Code", "Dynamic Load Cache"),
  q("Gaming & Internet", 3, "Welche Spielereihe schickt Spieler in die Welt von Azeroth?", "World of Warcraft", "Diablo", "EverQuest", "Guild Wars")
);

window.FRAGEN.push(

  /* ---------------- Essen & Trinken ---------------- */
  q("Essen & Trinken", 1, "Aus welcher Frucht wird Wein vergoren?", "Aus Weintrauben", "Aus Äpfeln", "Aus Beeren", "Aus Pflaumen"),
  q("Essen & Trinken", 1, "Woraus werden Pommes frites gemacht?", "Aus Kartoffeln", "Aus Maniok", "Aus Mais", "Aus Reis"),
  q("Essen & Trinken", 1, "Welches Getreide wird am häufigsten zu Brotmehl gemahlen?", "Weizen", "Hafer", "Hirse", "Buchweizen"),
  q("Essen & Trinken", 1, "Welche Frucht sorgt auf einer Pizza für die größten Diskussionen?", "Ananas", "Birne", "Feige", "Melone"),
  q("Essen & Trinken", 2, "Wie heißt der italienische Klassiker aus cremig gekochtem Reis?", "Risotto", "Polenta", "Gnocchi", "Panna cotta"),
  q("Essen & Trinken", 2, "Was ist Ricotta?", "Ein italienischer Frischkäse", "Eine Nudelsorte", "Ein Kräuteröl", "Eine Wurstsorte"),
  q("Essen & Trinken", 2, "Welche Nuss steckt in großen Mengen in Nuss-Nougat-Creme?", "Die Haselnuss", "Die Walnuss", "Die Mandel", "Die Erdnuss"),
  q("Essen & Trinken", 2, "Welches Gewürz färbt Currypulver gelb?", "Kurkuma", "Paprika", "Ingwer", "Senfsaat"),
  q("Essen & Trinken", 2, "Welches Kaffeegetränk besteht aus Espresso und viel Milchschaum?", "Cappuccino", "Americano", "Ristretto", "Macchiato"),
  q("Essen & Trinken", 2, "Was ist Couscous?", "Hartweizengrieß", "Eine Hülsenfrucht", "Eine Reissorte", "Ein Wurzelgemüse"),
  q("Essen & Trinken", 2, "Aus welchem Obst werden Rosinen getrocknet?", "Aus Weintrauben", "Aus Pflaumen", "Aus Kirschen", "Aus Aprikosen"),
  q("Essen & Trinken", 2, "Womit wird Sushi-Reis gesäuert?", "Mit Reisessig", "Mit Zitronensaft", "Mit Sojasauce", "Mit Mirin"),
  q("Essen & Trinken", 3, "Wie heißt die japanische Nudelsuppe mit Brühe, Ei und Fleisch?", "Ramen", "Udon", "Miso", "Soba"),
  q("Essen & Trinken", 3, "Welches Kraut ist die Hauptzutat von Pesto alla Genovese?", "Basilikum", "Petersilie", "Rucola", "Bärlauch"),
  q("Essen & Trinken", 3, "Woraus wird Sake gebraut?", "Aus Reis", "Aus Gerste", "Aus Hirse", "Aus Mais"),
  q("Essen & Trinken", 3, "Welches Land trinkt pro Kopf am meisten Kaffee?", "Finnland", "Italien", "Brasilien", "Österreich"),
  q("Essen & Trinken", 3, "Was bedeutet „al dente“?", "Bissfest gegart", "Sehr weich gekocht", "Roh serviert", "Scharf gewürzt"),
  q("Essen & Trinken", 3, "Welche Zutat lässt Brotteig aufgehen?", "Hefe", "Salz", "Zucker", "Butter"),
  q("Essen & Trinken", 3, "Wie heißt das französische Schmorgericht aus Sommergemüse?", "Ratatouille", "Cassoulet", "Bouillabaisse", "Quiche"),
  q("Essen & Trinken", 3, "Aus welchem Fleisch besteht ein original Wiener Schnitzel?", "Aus Kalbfleisch", "Aus Schweinefleisch", "Aus Putenfleisch", "Aus Rindfleisch"),
  q("Essen & Trinken", 3, "Was ist Miso?", "Eine Paste aus fermentierten Sojabohnen", "Ein Reisschnaps", "Eine Algensorte", "Ein Fischgewürz"),
  q("Essen & Trinken", 3, "Welcher Käse gehört auf eine echte Pizza Margherita?", "Mozzarella", "Gouda", "Parmesan", "Ricotta"),
  q("Essen & Trinken", 3, "Welcher Cocktail besteht aus Rum, Limette, Minze und Zucker?", "Mojito", "Caipirinha", "Daiquiri", "Cuba Libre"),
  q("Essen & Trinken", 3, "Von welchem Kontinent stammt die Kartoffel ursprünglich?", "Aus Südamerika", "Aus Asien", "Aus Afrika", "Aus Europa"),
  q("Essen & Trinken", 3, "Welche Zutat unterscheidet Vollmilchschokolade von Zartbitterschokolade?", "Milchpulver", "Mehr Kakao", "Honig", "Vanille"),

  /* ---------------- Natur & Tiere ---------------- */
  q("Natur & Tiere", 1, "Wie heißt das Junge eines Hundes?", "Welpe", "Fohlen", "Kitz", "Ferkel"),
  q("Natur & Tiere", 1, "Welches Tier baut Dämme aus Ästen?", "Der Biber", "Der Otter", "Der Dachs", "Die Bisamratte"),
  q("Natur & Tiere", 1, "Wie viele Flügel hat ein Schmetterling?", "4", "2", "6", "8"),
  q("Natur & Tiere", 1, "Was sammeln Eichhörnchen als Wintervorrat?", "Nüsse", "Pilze", "Blätter", "Beeren"),
  q("Natur & Tiere", 1, "Womit atmen Fische?", "Mit Kiemen", "Mit Lungen", "Über die Haut", "Mit Tracheen"),
  q("Natur & Tiere", 2, "Wie heißt der Nachwuchs eines Frosches?", "Kaulquappe", "Larve", "Nymphe", "Rogen"),
  q("Natur & Tiere", 2, "Welcher Vogel ist das Wappentier der USA?", "Der Weißkopfseeadler", "Der Steinadler", "Der Truthahn", "Der Kondor"),
  q("Natur & Tiere", 2, "Welche Tiere leben in einem Rudel?", "Wölfe", "Bienen", "Fische", "Schildkröten"),
  q("Natur & Tiere", 2, "Wie viele Zähne hat ein erwachsener Hund?", "42", "32", "28", "56"),
  q("Natur & Tiere", 2, "Welcher Baum ist an seiner weißen Rinde zu erkennen?", "Die Birke", "Die Erle", "Die Ulme", "Die Esche"),
  q("Natur & Tiere", 2, "Wie viele Punkte hat der in Europa häufigste Marienkäfer?", "7", "5", "9", "2"),
  q("Natur & Tiere", 2, "Welche Blume gilt als Symbol der Niederlande?", "Die Tulpe", "Die Narzisse", "Die Nelke", "Die Lilie"),
  q("Natur & Tiere", 2, "Wie heißt die männliche Biene im Bienenstock?", "Drohne", "Arbeiter", "König", "Weisel"),
  q("Natur & Tiere", 2, "Welches Tier hat einen Schnabel, legt Eier und ist trotzdem ein Säugetier?", "Das Schnabeltier", "Der Pinguin", "Der Ameisenbär", "Das Gürteltier"),
  q("Natur & Tiere", 3, "Welches Tier kann seine Hautfarbe der Umgebung anpassen?", "Das Chamäleon", "Der Gecko", "Der Leguan", "Die Eidechse"),
  q("Natur & Tiere", 3, "Welche ist die schwerste Schlange der Welt?", "Die Anakonda", "Die Königskobra", "Die Python", "Die Boa constrictor"),
  q("Natur & Tiere", 3, "Wie viele Beine hat ein Hummer?", "10", "8", "6", "12"),
  q("Natur & Tiere", 3, "Wie nennt man den Winterschlaf von Bären fachlich korrekt?", "Winterruhe", "Winterschlaf", "Winterstarre", "Kältestarre"),
  q("Natur & Tiere", 3, "Welches Tier hat die größten Augen im Tierreich?", "Der Riesenkalmar", "Der Blauwal", "Der Strauß", "Das Pferd"),
  q("Natur & Tiere", 3, "Welche Pflanze wächst am schnellsten?", "Bambus", "Efeu", "Weide", "Schilf"),
  q("Natur & Tiere", 3, "Wie nennt man die jährliche Reise der Zugvögel?", "Vogelzug", "Schwarmflug", "Wanderflug", "Zugwechsel"),
  q("Natur & Tiere", 3, "Welches Tier gilt in vielen Kulturen als Symbol der Weisheit?", "Die Eule", "Der Rabe", "Der Fuchs", "Die Schlange"),
  q("Natur & Tiere", 3, "Welcher Fisch schwimmt zum Laichen flussaufwärts?", "Der Lachs", "Der Hecht", "Der Karpfen", "Der Zander"),
  q("Natur & Tiere", 3, "Wie viele Pinguinarten leben wild am Nordpol?", "Keine", "Zwei", "Fünf", "Eine"),
  q("Natur & Tiere", 3, "Wie nennt man Tiere, die vor allem nachts aktiv sind?", "Nachtaktiv", "Tagaktiv", "Dämmerungsscheu", "Standorttreu")
);

window.FRAGEN.push(

  /* ---------------- Sprache & Wörter ---------------- */
  q("Sprache & Wörter", 1, "Wie viele Umlaute hat das deutsche Alphabet?", "3", "2", "4", "5"),
  q("Sprache & Wörter", 1, "Was heißt „Hallo“ auf Spanisch?", "Hola", "Ciao", "Bonjour", "Olá"),
  q("Sprache & Wörter", 1, "Was heißt „Danke“ auf Französisch?", "Merci", "Gracias", "Grazie", "Obrigado"),
  q("Sprache & Wörter", 1, "Wie viele Fälle kennt die deutsche Grammatik?", "4", "3", "5", "6"),
  q("Sprache & Wörter", 1, "Wie nennt man ein Wort, das eine Tätigkeit beschreibt?", "Verb", "Substantiv", "Adjektiv", "Pronomen"),
  q("Sprache & Wörter", 2, "Was bedeutet „ins Fettnäpfchen treten“?", "Etwas Peinliches sagen oder tun", "Sich sehr freuen", "Reich werden", "Zu spät kommen"),
  q("Sprache & Wörter", 2, "Was ist ein Synonym?", "Ein Wort mit gleicher oder ähnlicher Bedeutung", "Ein Gegenwort", "Ein Fremdwort", "Ein Reimwort"),
  q("Sprache & Wörter", 2, "Welche Sprache hat weltweit die meisten Muttersprachler?", "Chinesisch", "Englisch", "Spanisch", "Hindi"),
  q("Sprache & Wörter", 2, "Was bedeutet „Tomaten auf den Augen haben“?", "Etwas Offensichtliches nicht sehen", "Geweint haben", "Müde sein", "Sich schämen"),
  q("Sprache & Wörter", 2, "Aus welcher Sprache stammen die meisten Fachbegriffe der Wissenschaft?", "Aus dem Lateinischen", "Aus dem Arabischen", "Aus dem Französischen", "Aus dem Deutschen"),
  q("Sprache & Wörter", 2, "Was heißt „Tschüss“ auf Italienisch?", "Ciao", "Adiós", "Salut", "Tot ziens"),
  q("Sprache & Wörter", 2, "Wie lautet die Mehrzahl von „Atlas“?", "Atlanten", "Atlasse", "Atlase", "Atlaten"),
  q("Sprache & Wörter", 3, "Was bedeutet „lakonisch“?", "Kurz und knapp", "Umständlich", "Wütend", "Fröhlich"),
  q("Sprache & Wörter", 3, "Wie heißt das Satzzeichen „;“?", "Semikolon", "Kolon", "Apostroph", "Ellipse"),
  q("Sprache & Wörter", 3, "Was bedeutet „jemandem einen Bären aufbinden“?", "Jemanden anlügen", "Jemandem helfen", "Jemanden erschrecken", "Jemanden loben"),
  q("Sprache & Wörter", 3, "Wie nennt man ein Wort aus Anfangsbuchstaben wie „NATO“?", "Akronym", "Homonym", "Pseudonym", "Toponym"),
  q("Sprache & Wörter", 3, "Was bedeutet „obsolet“?", "Veraltet und überholt", "Zwingend nötig", "Geheim", "Übertrieben"),
  q("Sprache & Wörter", 3, "Was ist eine Metapher?", "Ein bildhafter Ausdruck ohne „wie“", "Eine Übertreibung", "Eine Wiederholung", "Eine rhetorische Frage"),
  q("Sprache & Wörter", 3, "Welche Sprache wird in Brasilien gesprochen?", "Portugiesisch", "Spanisch", "Brasilianisch", "Französisch"),
  q("Sprache & Wörter", 3, "Was bedeutet „Pi mal Daumen“?", "Grob geschätzt", "Exakt berechnet", "Sehr langsam", "Im Kreis herum"),
  q("Sprache & Wörter", 3, "Wie lautet die Mehrzahl von „Praktikum“?", "Praktika", "Praktikums", "Praktiken", "Praktikas"),
  q("Sprache & Wörter", 3, "Was bedeutet „eloquent“?", "Redegewandt", "Schweigsam", "Vergesslich", "Vornehm"),
  q("Sprache & Wörter", 3, "Was ist ein Anglizismus?", "Ein aus dem Englischen übernommenes Wort", "Ein englischer Grammatikfehler", "Ein englischer Dialekt", "Eine britische Redewendung"),
  q("Sprache & Wörter", 3, "Wie nennt man Wörter, die gleich klingen, aber verschieden geschrieben werden?", "Homophone", "Synonyme", "Antonyme", "Akronyme"),
  q("Sprache & Wörter", 3, "Was bedeutet die Redewendung „auf dem Holzweg sein“?", "Sich irren", "Verloren gehen", "Fleißig arbeiten", "Pleite sein"),

  /* ---------------- Marken & Logos ---------------- */
  q("Marken & Logos", 1, "Welche Automarke hat vier Ringe im Logo?", "Audi", "BMW", "Opel", "Toyota"),
  q("Marken & Logos", 1, "Welches Unternehmen hat einen angebissenen Apfel als Logo?", "Apple", "Android", "Samsung", "Alphabet"),
  q("Marken & Logos", 1, "Welche Fast-Food-Kette erkennt man am goldenen „M“?", "McDonald’s", "Burger King", "Subway", "KFC"),
  q("Marken & Logos", 1, "Welche Automarke hat einen Stern mit drei Zacken?", "Mercedes-Benz", "Chrysler", "Volvo", "Mitsubishi"),
  q("Marken & Logos", 1, "Welcher Sportartikelhersteller wirbt mit drei Streifen?", "Adidas", "Nike", "Puma", "Reebok"),
  q("Marken & Logos", 2, "Welche Marke steht hinter dem Slogan „Just Do It“?", "Nike", "Adidas", "Under Armour", "Asics"),
  q("Marken & Logos", 2, "Aus welchem Land kommt IKEA?", "Schweden", "Norwegen", "Dänemark", "Niederlande"),
  q("Marken & Logos", 2, "Welche Kette hat eine Meerjungfrau im Logo?", "Starbucks", "Costa Coffee", "Tchibo", "Dunkin’"),
  q("Marken & Logos", 2, "Welche Automarke zeigt eine springende Raubkatze?", "Jaguar", "Peugeot", "Lamborghini", "Abarth"),
  q("Marken & Logos", 2, "Wofür stehen die Buchstaben „BMW“?", "Bayerische Motoren Werke", "Bayerische Maschinen Werke", "Berliner Motoren Werke", "Bayrisch Münchner Werke"),
  q("Marken & Logos", 2, "Aus welchem Land stammt die Automarke Toyota?", "Japan", "Südkorea", "China", "Taiwan"),
  q("Marken & Logos", 2, "Welche Modemarke trägt ein Krokodil auf der Brust?", "Lacoste", "Ralph Lauren", "Tommy Hilfiger", "Fred Perry"),
  q("Marken & Logos", 2, "Aus welchem Land kommt die Automarke Volvo?", "Schweden", "Deutschland", "Frankreich", "Belgien"),
  q("Marken & Logos", 2, "Welche Getränkemarke nutzt seit über 100 Jahren einen roten Schwungschriftzug?", "Coca-Cola", "Pepsi", "Fanta", "Dr Pepper"),
  q("Marken & Logos", 3, "Aus welchem Land stammt der Bausteinhersteller Lego?", "Dänemark", "Schweden", "Deutschland", "Niederlande"),
  q("Marken & Logos", 3, "Wie heißt der Mutterkonzern von Facebook, Instagram und WhatsApp?", "Meta", "Alphabet", "Bytedance", "Tencent"),
  q("Marken & Logos", 3, "Welche italienische Automarke zeigt ein schwarzes Pferd im Logo?", "Ferrari", "Maserati", "Alfa Romeo", "Fiat"),
  q("Marken & Logos", 3, "Aus welchem Land kommt die Marke Nokia?", "Finnland", "Schweden", "Japan", "Estland"),
  q("Marken & Logos", 3, "Welcher Konzern besitzt Škoda, SEAT und Porsche?", "Volkswagen", "BMW", "Stellantis", "Daimler"),
  q("Marken & Logos", 3, "Welche zwei Sportmarken gründeten zwei zerstrittene Brüder in Herzogenaurach?", "Adidas und Puma", "Nike und Reebok", "Fila und Kappa", "Jack Wolfskin und Vaude"),
  q("Marken & Logos", 3, "Aus welchem Land stammt Samsung?", "Südkorea", "Japan", "China", "Singapur"),
  q("Marken & Logos", 3, "Wie heißt die größte Fluggesellschaft Deutschlands?", "Lufthansa", "Condor", "Eurowings", "TUI fly"),
  q("Marken & Logos", 3, "Welches Unternehmen stellt die PlayStation her?", "Sony", "Panasonic", "Sharp", "Toshiba"),
  q("Marken & Logos", 3, "Welcher Konzern steckt hinter Nutella?", "Ferrero", "Nestlé", "Mondelez", "Dr. Oetker"),
  q("Marken & Logos", 3, "Welche Farbe hat der Hintergrund des Logos der Deutschen Bahn?", "Rot", "Blau", "Grün", "Grau")
);

window.FRAGEN.push(

  /* ---------------- Weitere Ja/Nein-Fragen ---------------- */
  jn("Allgemeinwissen", 1, "Hat ein Jahr genau 52 Wochen?", false),
  jn("Allgemeinwissen", 2, "War Deutschland Gründungsmitglied der Vereinten Nationen?", false),
  jn("Allgemeinwissen", 2, "Gilt auf allen deutschen Autobahnen ein Tempolimit?", false),
  jn("Allgemeinwissen", 3, "Ist der Bundespräsident der Regierungschef Deutschlands?", false),

  jn("Geografie", 1, "Ist Australien gleichzeitig ein Land und ein Kontinent?", true),
  jn("Geografie", 2, "Liegt Prag westlicher als Wien?", true),
  jn("Geografie", 2, "Ist die Türkei Mitglied der Europäischen Union?", false),
  jn("Geografie", 3, "Liegt Afrika vollständig auf der Südhalbkugel?", false),
  jn("Geografie", 3, "Ist Grönland ein eigenständiger Staat?", false),

  jn("Geschichte", 2, "Wurde die Titanic in Deutschland gebaut?", false),
  jn("Geschichte", 2, "War die DDR Mitglied der NATO?", false),
  jn("Geschichte", 3, "Regierte Königin Victoria länger als 60 Jahre?", true),
  jn("Geschichte", 3, "War Albert Einstein jemals Präsident Israels?", false),

  jn("Wissenschaft", 1, "Dreht sich die Erde um die Sonne?", true),
  jn("Wissenschaft", 2, "Ist Schall schneller als Licht?", false),
  jn("Wissenschaft", 3, "Kann Wasser auch unter 100 Grad Celsius kochen?", true),
  jn("Wissenschaft", 3, "Sind alle Metalle magnetisch?", false),

  jn("Sport", 2, "Darf man beim Volleyball den Ball mit dem Fuß spielen?", true),
  jn("Sport", 2, "Ist die Formel 1 eine olympische Disziplin?", false),
  jn("Sport", 3, "Haben alle Fußballfelder exakt dieselben Maße?", false),

  jn("Musik", 2, "Hat Elvis Presley eine Zeit lang in Deutschland gelebt?", true),
  jn("Musik", 2, "Zählt das Klavier fachlich auch zu den Schlaginstrumenten?", true),
  jn("Musik", 3, "Wurde die Melodie von „Happy Birthday“ ursprünglich als Geburtstagslied geschrieben?", false),

  jn("Film & TV", 2, "Wurde „Der Herr der Ringe“ in Neuseeland gedreht?", true),
  jn("Film & TV", 2, "Gehört das Filmstudio Pixar zu Disney?", true),
  jn("Film & TV", 3, "Liegt das Springfield der Simpsons in einem real benannten US-Bundesstaat?", false),

  jn("Gaming & Internet", 2, "Kann man Minecraft auch ohne Internetverbindung spielen?", true),
  jn("Gaming & Internet", 2, "Ist Nintendo ein japanisches Unternehmen?", true),
  jn("Gaming & Internet", 3, "Wurde Nintendo ursprünglich als Spielkartenhersteller gegründet?", true),

  jn("Essen & Trinken", 2, "Ist Honig für Säuglinge unbedenklich?", false),
  jn("Essen & Trinken", 2, "Ist die Cashew botanisch gesehen eine Nuss?", false),
  jn("Essen & Trinken", 3, "Verdirbt Honig nach wenigen Jahren zwangsläufig?", false),

  jn("Natur & Tiere", 2, "Können Kühe Treppen hinaufsteigen?", true),
  jn("Natur & Tiere", 2, "Ist wissenschaftlich belegt, dass Elefanten Angst vor Mäusen haben?", false),
  jn("Natur & Tiere", 3, "Sind Wale Säugetiere?", true),

  jn("Sprache & Wörter", 1, "Schreibt man Substantive im Deutschen groß?", true),
  jn("Sprache & Wörter", 2, "Gibt es im Deutschen mehr als drei bestimmte Artikel?", false),
  jn("Sprache & Wörter", 3, "Stammt das englische Wort „kindergarten“ aus dem Deutschen?", true),

  jn("Marken & Logos", 2, "Gehört YouTube zu Google?", true),
  jn("Marken & Logos", 2, "Ist Red Bull eine österreichische Marke?", true),
  jn("Marken & Logos", 3, "Wurde Adidas nach seinem Gründer Adolf Dassler benannt?", true)
);
