/*
 * Fragenkatalog für "Der Dümmste fliegt"
 * ---------------------------------------
 * q(kategorie, schwierigkeit, frage, richtigeAntwort, ...falscheAntworten)
 * schwierigkeit: 1 = leicht, 2 = mittel, 3 = schwer
 * Die Antworten werden im Spiel zufällig gemischt.
 */
const q = (k, s, f, r, ...w) => ({ k, s, f, r, w });

window.FRAGEN = [

  /* ---------------- Allgemeinwissen ---------------- */
  q("Allgemeinwissen", 1, "Wie viele Farben hat ein Regenbogen klassischerweise?", "7", "5", "6", "9"),
  q("Allgemeinwissen", 1, "Welche Farbe entsteht, wenn man Blau und Gelb mischt?", "Grün", "Orange", "Lila", "Braun"),
  q("Allgemeinwissen", 1, "Wie viele Buchstaben hat das deutsche Alphabet ohne Umlaute und ß?", "26", "24", "28", "30"),
  q("Allgemeinwissen", 1, "Wie viele Sekunden hat eine Stunde?", "3.600", "360", "6.000", "1.800"),
  q("Allgemeinwissen", 1, "Welches Verkehrsschild ist achteckig?", "Das Stoppschild", "Vorfahrt achten", "Halteverbot", "Einbahnstraße"),
  q("Allgemeinwissen", 1, "Wie viele Bundesländer hat Deutschland?", "16", "14", "17", "12"),
  q("Allgemeinwissen", 1, "Welche Währung gilt in der Schweiz?", "Schweizer Franken", "Euro", "Krone", "Schilling"),
  q("Allgemeinwissen", 1, "Wie viele Karten hat ein deutsches Skatblatt?", "32", "52", "36", "24"),
  q("Allgemeinwissen", 1, "Wie viele Ecken hat ein Würfel?", "8", "6", "12", "4"),
  q("Allgemeinwissen", 1, "Wie viele Nullen hat eine Million?", "6", "3", "9", "12"),
  q("Allgemeinwissen", 1, "Wie viele Grad hat ein voller Kreis?", "360", "180", "270", "400"),
  q("Allgemeinwissen", 1, "Wie viele Felder hat ein Schachbrett?", "64", "48", "81", "100"),
  q("Allgemeinwissen", 2, "Wie viele Bit sind ein Byte?", "8", "4", "16", "10"),
  q("Allgemeinwissen", 2, "Was misst ein Barometer?", "Den Luftdruck", "Die Temperatur", "Die Luftfeuchtigkeit", "Die Windstärke"),
  q("Allgemeinwissen", 2, "Welche römische Zahl steht für 50?", "L", "C", "D", "X"),
  q("Allgemeinwissen", 2, "Wie viele Streifen hat die Flagge der USA?", "13", "50", "12", "15"),
  q("Allgemeinwissen", 2, "Wofür steht die Abkürzung „WLAN“?", "Wireless Local Area Network", "Wide Line Access Network", "Wireless Link And Net", "Web Local Access Node"),
  q("Allgemeinwissen", 2, "Welche Blutgruppe gilt als Universalspender?", "0 negativ", "AB positiv", "A positiv", "B negativ"),
  q("Allgemeinwissen", 2, "Wie viele Zähne hat ein erwachsener Mensch normalerweise?", "32", "28", "30", "36"),
  q("Allgemeinwissen", 2, "Wie viele Grad hat ein rechter Winkel?", "90", "45", "180", "120"),
  q("Allgemeinwissen", 2, "Was bedeutet „ASAP“?", "As soon as possible", "Always send a photo", "As said and posted", "After school, after practice"),
  q("Allgemeinwissen", 2, "Wie viele Sekunden hat ein Tag?", "86.400", "36.000", "144.000", "60.000"),
  q("Allgemeinwissen", 2, "Was bedeutet die Abkürzung „GmbH“?", "Gesellschaft mit beschränkter Haftung", "Gemeinschaft mit betrieblicher Haftung", "Gesellschaft mit betrieblichem Handel", "Genossenschaft mit begrenzter Haftung"),
  q("Allgemeinwissen", 2, "Was bedeutet der Ausdruck „vice versa“?", "Umgekehrt", "Sofort", "Zum Wohl", "Erst recht"),
  q("Allgemeinwissen", 3, "Wie viele Zeitzonen hat Russland?", "11", "7", "9", "14"),
  q("Allgemeinwissen", 3, "Was ist ein Palindrom?", "Ein Wort, das vorwärts wie rückwärts gleich gelesen wird", "Ein Wort mit doppelter Bedeutung", "Ein Wort ohne Vokale", "Ein Wort aus zwei Sprachen"),
  q("Allgemeinwissen", 3, "Welche Farbe hat die sogenannte „Blackbox“ in einem Flugzeug wirklich?", "Orange", "Schwarz", "Rot", "Silber"),
  q("Allgemeinwissen", 3, "Wofür steht „SOS“ ursprünglich?", "Für gar nichts – es ist nur ein einprägsames Morsezeichen", "Save Our Souls", "Send Out Ships", "Stop Other Signals"),
  q("Allgemeinwissen", 3, "Wie viel Prozent der Erdoberfläche sind ungefähr von Wasser bedeckt?", "71 %", "50 %", "61 %", "85 %"),
  q("Allgemeinwissen", 3, "Welches deutsche Gericht entscheidet über Verfassungsfragen?", "Das Bundesverfassungsgericht", "Der Bundesgerichtshof", "Das Bundesverwaltungsgericht", "Der Bundesrat"),

  /* ---------------- Geografie ---------------- */
  q("Geografie", 1, "Wie heißt die Hauptstadt von Italien?", "Rom", "Mailand", "Neapel", "Turin"),
  q("Geografie", 1, "Welcher ist der größte Ozean der Erde?", "Der Pazifik", "Der Atlantik", "Der Indische Ozean", "Das Nordpolarmeer"),
  q("Geografie", 1, "Wie viele Kontinente gibt es?", "7", "5", "6", "8"),
  q("Geografie", 1, "In welcher Stadt steht die Freiheitsstatue?", "New York", "Washington", "Boston", "Philadelphia"),
  q("Geografie", 1, "Welcher Fluss fließt durch Paris?", "Die Seine", "Die Loire", "Die Rhône", "Die Themse"),
  q("Geografie", 1, "Welches Land grenzt im Norden an Deutschland?", "Dänemark", "Norwegen", "Schweden", "Polen"),
  q("Geografie", 1, "Wie heißt der höchste Berg der Welt?", "Mount Everest", "K2", "Mont Blanc", "Kilimandscharo"),
  q("Geografie", 1, "Welcher Kontinent hat die meisten Einwohner?", "Asien", "Afrika", "Europa", "Nordamerika"),
  q("Geografie", 1, "Welche Wüste ist die größte heiße Wüste der Welt?", "Die Sahara", "Die Gobi", "Die Kalahari", "Die Atacama"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Australien?", "Canberra", "Sydney", "Melbourne", "Perth"),
  q("Geografie", 2, "Wie heißt der höchste Berg Deutschlands?", "Die Zugspitze", "Der Brocken", "Der Feldberg", "Der Watzmann"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Kanada?", "Ottawa", "Toronto", "Vancouver", "Montreal"),
  q("Geografie", 2, "Wie heißt die Hauptstadt der Türkei?", "Ankara", "Istanbul", "Izmir", "Antalya"),
  q("Geografie", 2, "Welches Land hat heute die meisten Einwohner?", "Indien", "China", "USA", "Indonesien"),
  q("Geografie", 2, "In welchem Land liegt die Stadt Marrakesch?", "Marokko", "Ägypten", "Tunesien", "Algerien"),
  q("Geografie", 2, "Welches Meer liegt zwischen Europa und Afrika?", "Das Mittelmeer", "Das Schwarze Meer", "Das Rote Meer", "Die Nordsee"),
  q("Geografie", 2, "Wie heißt die Hauptstadt von Brasilien?", "Brasília", "Rio de Janeiro", "São Paulo", "Salvador"),
  q("Geografie", 2, "Wie viele Sterne hat die Flagge der Europäischen Union?", "12", "15", "27", "9"),
  q("Geografie", 2, "Welcher Fluss fließt durch Wien?", "Die Donau", "Der Rhein", "Die Elbe", "Die Mosel"),
  q("Geografie", 2, "Welcher Fluss ist auf deutschem Gebiet am längsten?", "Der Rhein", "Die Elbe", "Die Donau", "Die Weser"),
  q("Geografie", 3, "Welches ist das flächenmäßig kleinste Land der Welt?", "Vatikanstadt", "Monaco", "San Marino", "Liechtenstein"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Neuseeland?", "Wellington", "Auckland", "Christchurch", "Dunedin"),
  q("Geografie", 3, "Welches Land hat die längste Küstenlinie der Welt?", "Kanada", "Russland", "Australien", "Indonesien"),
  q("Geografie", 3, "In welchem Bundesland liegt Erfurt?", "Thüringen", "Sachsen", "Sachsen-Anhalt", "Hessen"),
  q("Geografie", 3, "Welches Land wird „Land der tausend Seen“ genannt?", "Finnland", "Schweden", "Kanada", "Estland"),
  q("Geografie", 3, "Welche Meerenge trennt Europa von Afrika?", "Die Straße von Gibraltar", "Der Bosporus", "Der Ärmelkanal", "Die Straße von Hormus"),
  q("Geografie", 3, "Wie heißt die Hauptstadt von Kasachstan?", "Astana", "Almaty", "Taschkent", "Bischkek"),
  q("Geografie", 3, "Welcher See ist der tiefste der Welt?", "Der Baikalsee", "Der Titicacasee", "Der Viktoriasee", "Der Kaspische See"),
  q("Geografie", 3, "An welches einzige Land grenzt Portugal?", "Spanien", "Frankreich", "Marokko", "Andorra"),
  q("Geografie", 3, "Welcher See ist der größte, der vollständig in Deutschland liegt?", "Die Müritz", "Der Bodensee", "Der Chiemsee", "Der Starnberger See"),

  /* ---------------- Geschichte ---------------- */
  q("Geschichte", 1, "In welchem Jahr fiel die Berliner Mauer?", "1989", "1987", "1990", "1991"),
  q("Geschichte", 1, "In welchem Jahr begann der Zweite Weltkrieg?", "1939", "1938", "1940", "1941"),
  q("Geschichte", 1, "Wer betrat 1969 als erster Mensch den Mond?", "Neil Armstrong", "Buzz Aldrin", "Juri Gagarin", "Michael Collins"),
  q("Geschichte", 1, "In welchem Jahr wurde Deutschland wiedervereinigt?", "1990", "1989", "1991", "1992"),
  q("Geschichte", 1, "Welches berühmte Schiff sank im Jahr 1912?", "Die Titanic", "Die Lusitania", "Die Bismarck", "Die Mary Rose"),
  q("Geschichte", 1, "Wer war die erste Bundeskanzlerin Deutschlands?", "Angela Merkel", "Annalena Baerbock", "Ursula von der Leyen", "Hannelore Kraft"),
  q("Geschichte", 1, "Wer war der erste Präsident der USA?", "George Washington", "Abraham Lincoln", "Thomas Jefferson", "Benjamin Franklin"),
  q("Geschichte", 2, "Wer war der erste Bundeskanzler der Bundesrepublik Deutschland?", "Konrad Adenauer", "Ludwig Erhard", "Willy Brandt", "Helmut Schmidt"),
  q("Geschichte", 2, "Wer gilt als der erste römische Kaiser?", "Augustus", "Julius Caesar", "Nero", "Konstantin"),
  q("Geschichte", 2, "In welchem Jahr endete der Erste Weltkrieg?", "1918", "1916", "1919", "1920"),
  q("Geschichte", 2, "Wer erfand in Europa den Buchdruck mit beweglichen Lettern?", "Johannes Gutenberg", "Martin Luther", "Leonardo da Vinci", "Nikolaus Kopernikus"),
  q("Geschichte", 2, "In welchem Jahr erreichte Christoph Kolumbus Amerika?", "1492", "1453", "1517", "1520"),
  q("Geschichte", 2, "Wessen Grab entdeckte Howard Carter im Jahr 1922?", "Tutanchamun", "Ramses II.", "Cheops", "Echnaton"),
  q("Geschichte", 2, "Was schlug Martin Luther 1517 in Wittenberg an?", "95 Thesen", "Die Bibelübersetzung", "Den Augsburger Religionsfrieden", "Die Goldene Bulle"),
  q("Geschichte", 2, "Wie nennt man die Zeit der Ost-West-Spannungen nach 1945?", "Der Kalte Krieg", "Die Restauration", "Die Blockzeit", "Der Stellungskrieg"),
  q("Geschichte", 2, "Wie hieß der berühmte Anführer der Hunnen?", "Attila", "Dschingis Khan", "Hannibal", "Spartacus"),
  q("Geschichte", 2, "Wer war Bundeskanzler zur Zeit der deutschen Wiedervereinigung?", "Helmut Kohl", "Gerhard Schröder", "Helmut Schmidt", "Willy Brandt"),
  q("Geschichte", 3, "Wer war der letzte deutsche Kaiser?", "Wilhelm II.", "Friedrich III.", "Wilhelm I.", "Ludwig II."),
  q("Geschichte", 3, "In welchem Jahr wurde die DDR gegründet?", "1949", "1945", "1953", "1961"),
  q("Geschichte", 3, "Mit wem schrieb Friedrich Engels das „Kommunistische Manifest“?", "Karl Marx", "Lenin", "Rosa Luxemburg", "August Bebel"),
  q("Geschichte", 3, "Welches antike Weltwunder stand in Alexandria?", "Der Leuchtturm von Pharos", "Der Koloss von Rhodos", "Die Hängenden Gärten", "Der Zeus-Tempel"),
  q("Geschichte", 3, "In welchem Jahr stürmten Pariser die Bastille?", "1789", "1776", "1799", "1815"),
  q("Geschichte", 3, "Bei welcher Schlacht erlitt Napoleon 1815 seine endgültige Niederlage?", "Bei Waterloo", "Bei Leipzig", "Bei Austerlitz", "Bei Trafalgar"),
  q("Geschichte", 3, "Wie hieß der erste künstliche Satellit der Erde?", "Sputnik 1", "Apollo 1", "Explorer 1", "Wostok 1"),
  q("Geschichte", 3, "Welche Stadt wurde 79 n. Chr. durch den Ausbruch des Vesuvs verschüttet?", "Pompeji", "Rom", "Neapel", "Karthago"),
  q("Geschichte", 3, "In welchem Jahr wurde die Berliner Mauer gebaut?", "1961", "1949", "1953", "1968"),
  q("Geschichte", 3, "Welche Königsdynastie herrschte in Frankreich vor der Revolution?", "Die Bourbonen", "Die Habsburger", "Die Tudors", "Die Romanows"),
  q("Geschichte", 3, "In welchem Jahrhundert lebte Martin Luther?", "Im 16. Jahrhundert", "Im 14. Jahrhundert", "Im 15. Jahrhundert", "Im 17. Jahrhundert"),
  q("Geschichte", 3, "Welche britische Königin regierte von 1952 bis 2022?", "Elizabeth II.", "Victoria", "Elizabeth I.", "Mary II."),
  q("Geschichte", 3, "In welchem Jahr wurde die Bundesrepublik Deutschland gegründet?", "1949", "1945", "1948", "1950"),

  /* ---------------- Wissenschaft ---------------- */
  q("Wissenschaft", 1, "Welche chemische Formel hat Wasser?", "H₂O", "CO₂", "O₂", "H₂O₂"),
  q("Wissenschaft", 1, "Wie viele Planeten hat unser Sonnensystem?", "8", "9", "7", "10"),
  q("Wissenschaft", 1, "Welcher Planet ist der Sonne am nächsten?", "Merkur", "Venus", "Mars", "Erde"),
  q("Wissenschaft", 1, "Was ist das größte Organ des Menschen?", "Die Haut", "Die Leber", "Die Lunge", "Der Darm"),
  q("Wissenschaft", 1, "Welcher Planet wird auch „der rote Planet“ genannt?", "Mars", "Jupiter", "Venus", "Merkur"),
  q("Wissenschaft", 1, "Wie heißt die Galaxie, in der wir leben?", "Die Milchstraße", "Andromeda", "Der Orionnebel", "Die Magellansche Wolke"),
  q("Wissenschaft", 1, "Wie heißt der größte Planet unseres Sonnensystems?", "Jupiter", "Saturn", "Neptun", "Uranus"),
  q("Wissenschaft", 1, "Wie nennt man den Vorgang, bei dem Pflanzen Licht in Energie umwandeln?", "Fotosynthese", "Osmose", "Verdunstung", "Zellatmung"),
  q("Wissenschaft", 1, "Bei wie viel Grad Celsius siedet Wasser auf Meereshöhe?", "100", "90", "80", "120"),
  q("Wissenschaft", 2, "Welches chemische Symbol steht für Gold?", "Au", "Ag", "Go", "Gd"),
  q("Wissenschaft", 2, "Wie schnell ist Licht ungefähr?", "300.000 km/s", "3.000 km/s", "30.000 km/s", "3 Mio. km/s"),
  q("Wissenschaft", 2, "Wer entwickelte die Relativitätstheorie?", "Albert Einstein", "Isaac Newton", "Max Planck", "Niels Bohr"),
  q("Wissenschaft", 2, "Wie viele Chromosomenpaare hat ein Mensch?", "23", "24", "46", "12"),
  q("Wissenschaft", 2, "Was misst die Einheit Hertz?", "Die Frequenz", "Die Lautstärke", "Die Spannung", "Die Leistung"),
  q("Wissenschaft", 2, "Welches Element hat die Ordnungszahl 1?", "Wasserstoff", "Helium", "Sauerstoff", "Kohlenstoff"),
  q("Wissenschaft", 2, "Wofür steht die Abkürzung „CPU“?", "Central Processing Unit", "Computer Power Unit", "Control Program Unit", "Central Program Utility"),
  q("Wissenschaft", 2, "Wie viele Knochen hat ein erwachsener Mensch ungefähr?", "206", "150", "300", "412"),
  q("Wissenschaft", 2, "Welches Teilchen im Atom ist negativ geladen?", "Das Elektron", "Das Proton", "Das Neutron", "Das Photon"),
  q("Wissenschaft", 2, "Welche Einheit misst die elektrische Spannung?", "Volt", "Ampere", "Watt", "Ohm"),
  q("Wissenschaft", 2, "Welcher Naturforscher formulierte die Evolutionstheorie?", "Charles Darwin", "Gregor Mendel", "Carl von Linné", "Alexander von Humboldt"),
  q("Wissenschaft", 3, "Welches Metall ist bei Zimmertemperatur flüssig?", "Quecksilber", "Blei", "Zinn", "Natrium"),
  q("Wissenschaft", 3, "Welches Gas macht den größten Anteil unserer Atemluft aus?", "Stickstoff", "Sauerstoff", "Kohlendioxid", "Argon"),
  q("Wissenschaft", 3, "Was entdeckte Alexander Fleming im Jahr 1928?", "Penicillin", "Insulin", "Die Röntgenstrahlung", "Die DNA-Struktur"),
  q("Wissenschaft", 3, "Wie viel Prozent Sauerstoff enthält die Luft ungefähr?", "21 %", "35 %", "50 %", "78 %"),
  q("Wissenschaft", 3, "Wofür steht die Abkürzung „DNA“ im Deutschen?", "Desoxyribonukleinsäure", "Dinatriumacetat", "Doppelnukleinsäure", "Diaminonukleosid"),
  q("Wissenschaft", 3, "Welche Blutgefäße transportieren Blut vom Herzen weg?", "Arterien", "Venen", "Kapillaren", "Lymphgefäße"),
  q("Wissenschaft", 3, "Welcher Stoff ist im Universum am häufigsten?", "Wasserstoff", "Sauerstoff", "Helium", "Eisen"),
  q("Wissenschaft", 3, "Wie heißt die Wissenschaft, die Erdbeben erforscht?", "Seismologie", "Geodäsie", "Vulkanologie", "Meteorologie"),
  q("Wissenschaft", 3, "Wie nennt man die kleinste Einheit eines chemischen Elements?", "Das Atom", "Das Molekül", "Die Zelle", "Das Ion"),
  q("Wissenschaft", 3, "Welcher Planet hat das auffälligste Ringsystem?", "Saturn", "Jupiter", "Uranus", "Neptun"),

  /* ---------------- Sport ---------------- */
  q("Sport", 1, "Wie viele Spieler einer Fußballmannschaft stehen auf dem Platz?", "11", "10", "12", "9"),
  q("Sport", 1, "Wie lange dauert ein Fußballspiel regulär?", "90 Minuten", "60 Minuten", "80 Minuten", "120 Minuten"),
  q("Sport", 1, "Alle wie viele Jahre finden die Olympischen Sommerspiele statt?", "Alle 4 Jahre", "Alle 2 Jahre", "Alle 3 Jahre", "Alle 5 Jahre"),
  q("Sport", 1, "Wie viele Ringe hat das olympische Symbol?", "5", "4", "6", "3"),
  q("Sport", 1, "Wie viele Spieler einer Basketballmannschaft stehen auf dem Feld?", "5", "6", "7", "4"),
  q("Sport", 2, "Welches Land wurde 2014 Fußballweltmeister?", "Deutschland", "Argentinien", "Brasilien", "Spanien"),
  q("Sport", 2, "In welcher Sportart gibt es Grand-Slam-Turniere in Melbourne, Paris, London und New York?", "Tennis", "Golf", "Badminton", "Tischtennis"),
  q("Sport", 2, "Wie viele Punkte bringt ein Touchdown im American Football?", "6", "7", "3", "5"),
  q("Sport", 2, "Wie lang ist ein Marathon?", "42,195 km", "40 km", "45 km", "21,1 km"),
  q("Sport", 2, "In welchem Land fand die Fußball-WM 2018 statt?", "Russland", "Brasilien", "Katar", "Südafrika"),
  q("Sport", 2, "Wie viele Spieler einer Handballmannschaft stehen auf dem Feld?", "7", "6", "8", "5"),
  q("Sport", 2, "Auf welchem Gerät fährt man eine „Halfpipe“?", "Snowboard", "Rennrad", "Schlitten", "Skier mit Stöcken"),
  q("Sport", 2, "Welcher Verein ist deutscher Rekordmeister im Fußball?", "FC Bayern München", "Borussia Dortmund", "Hamburger SV", "FC Schalke 04"),
  q("Sport", 3, "Welcher Fußballer wurde „der Kaiser“ genannt?", "Franz Beckenbauer", "Gerd Müller", "Uwe Seeler", "Lothar Matthäus"),
  q("Sport", 3, "Aus wie vielen Löchern besteht eine Standard-Golfrunde?", "18", "9", "12", "24"),
  q("Sport", 3, "In welcher Sportart wurde Michael Schumacher siebenfacher Weltmeister?", "Formel 1", "MotoGP", "Rallye", "Superbike"),
  q("Sport", 3, "Welche Farbe hat das Trikot des Gesamtführenden bei der Tour de France?", "Gelb", "Grün", "Weiß", "Rot gepunktet"),
  q("Sport", 3, "Wie viele Spieler einer Volleyballmannschaft stehen auf dem Feld?", "6", "5", "7", "8"),
  q("Sport", 3, "Welches Land hat die meisten Fußball-Weltmeistertitel?", "Brasilien", "Deutschland", "Italien", "Argentinien"),
  q("Sport", 3, "Wie lange dauert ein Drittel im Eishockey?", "20 Minuten", "15 Minuten", "25 Minuten", "30 Minuten"),
  q("Sport", 3, "In welcher Höhe hängt ein Basketballkorb?", "3,05 m", "2,80 m", "3,50 m", "2,50 m"),
  q("Sport", 3, "In welcher Stadt fanden die Olympischen Sommerspiele 2021 statt?", "Tokio", "Peking", "Paris", "Rio de Janeiro"),
  q("Sport", 3, "Welcher Boxer nannte sich selbst „The Greatest“?", "Muhammad Ali", "Mike Tyson", "Joe Frazier", "George Foreman"),
  q("Sport", 3, "Wie viele Runden dauert ein WM-Boxkampf maximal?", "12", "10", "15", "8"),
  q("Sport", 3, "In welcher Stadt findet das Tennisturnier Wimbledon statt?", "London", "Manchester", "Melbourne", "Paris"),
  q("Sport", 3, "Wie viele Steine spielt ein Curling-Team pro End?", "8", "6", "10", "4"),
  q("Sport", 3, "Wie viele Gewinnsätze braucht ein Herren-Match bei einem Grand-Slam-Turnier?", "3", "2", "4", "5"),
  q("Sport", 3, "Welche Sportart wird bei der „Vierschanzentournee“ ausgeübt?", "Skispringen", "Abfahrtslauf", "Biathlon", "Bobfahren"),

  /* ---------------- Musik ---------------- */
  q("Musik", 1, "Wie viele Tasten hat ein Standard-Klavier?", "88", "76", "64", "100"),
  q("Musik", 1, "Welche Band sang „Bohemian Rhapsody“?", "Queen", "The Beatles", "Pink Floyd", "The Rolling Stones"),
  q("Musik", 1, "Wie viele Saiten hat eine klassische Gitarre?", "6", "4", "7", "12"),
  q("Musik", 1, "Wie nennt man die Person, die vor einem Orchester den Taktstock schwingt?", "Dirigent", "Komponist", "Solist", "Intendant"),
  q("Musik", 2, "Wer ist als „King of Pop“ bekannt?", "Michael Jackson", "Elvis Presley", "Prince", "Freddie Mercury"),
  q("Musik", 2, "Aus welcher Stadt stammen die Beatles?", "Liverpool", "London", "Manchester", "Birmingham"),
  q("Musik", 2, "Welches Instrument spielte Louis Armstrong?", "Trompete", "Saxofon", "Klavier", "Kontrabass"),
  q("Musik", 2, "Welche deutsche Band singt „Du hast“?", "Rammstein", "Die Toten Hosen", "Scorpions", "Die Ärzte"),
  q("Musik", 2, "Welche Sängerin veröffentlichte das Album „21“?", "Adele", "Amy Winehouse", "Beyoncé", "Rihanna"),
  q("Musik", 2, "Wie heißt der größte Musikwettbewerb Europas?", "Eurovision Song Contest", "MTV Europe Awards", "Grammy Europe", "Echo Festival"),
  q("Musik", 2, "Welche Sängerin ist für „Bad Romance“ bekannt?", "Lady Gaga", "Katy Perry", "Britney Spears", "Madonna"),
  q("Musik", 2, "Welche Band veröffentlichte „Smells Like Teen Spirit“?", "Nirvana", "Pearl Jam", "Soundgarden", "Green Day"),
  q("Musik", 2, "Aus wie vielen Mitgliedern bestanden die Beatles?", "4", "3", "5", "6"),
  q("Musik", 3, "Wer komponierte die Neunte Sinfonie mit der „Ode an die Freude“?", "Ludwig van Beethoven", "Wolfgang Amadeus Mozart", "Johann Sebastian Bach", "Franz Schubert"),
  q("Musik", 3, "Wer komponierte die Oper „Die Zauberflöte“?", "Wolfgang Amadeus Mozart", "Richard Wagner", "Giuseppe Verdi", "Joseph Haydn"),
  q("Musik", 3, "Wie nennt man ein Musikstück für vier Instrumente?", "Quartett", "Trio", "Quintett", "Duett"),
  q("Musik", 3, "Welcher Künstler sang „Purple Rain“?", "Prince", "Jimi Hendrix", "David Bowie", "Stevie Wonder"),
  q("Musik", 3, "Welche Band veröffentlichte „Stairway to Heaven“?", "Led Zeppelin", "Deep Purple", "Black Sabbath", "The Who"),
  q("Musik", 3, "Wer sang „Like a Rolling Stone“?", "Bob Dylan", "Neil Young", "Bruce Springsteen", "Johnny Cash"),
  q("Musik", 3, "Was bedeutet die Vortragsbezeichnung „forte“?", "Laut", "Leise", "Schnell", "Langsam"),
  q("Musik", 3, "Wer komponierte „Die vier Jahreszeiten“?", "Antonio Vivaldi", "Johann Sebastian Bach", "Georg Friedrich Händel", "Johann Pachelbel"),
  q("Musik", 3, "Was bedeutet „a cappella“?", "Gesang ohne Instrumentalbegleitung", "Gesang im Duett", "Sehr hoher Gesang", "Gesang in Latein"),
  q("Musik", 3, "Welcher Musiker wurde „Godfather of Soul“ genannt?", "James Brown", "Marvin Gaye", "Ray Charles", "Otis Redding"),
  q("Musik", 3, "Welches Album ist das meistverkaufte aller Zeiten?", "„Thriller“ von Michael Jackson", "„Back in Black“ von AC/DC", "„The Dark Side of the Moon“", "„Abbey Road“"),
  q("Musik", 3, "Welche Tonart hat weder Kreuze noch Bs?", "C-Dur", "G-Dur", "F-Dur", "D-Dur"),
  q("Musik", 3, "Aus welchem Land stammt der Tango ursprünglich?", "Argentinien", "Spanien", "Brasilien", "Kuba"),

  /* ---------------- Film & TV ---------------- */
  q("Film & TV", 1, "Wie heißt der Zauberschüler aus den Romanen von J. K. Rowling?", "Harry Potter", "Percy Jackson", "Ron Weasley", "Frodo Beutlin"),
  q("Film & TV", 1, "In welcher Filmreihe sagt man „Möge die Macht mit dir sein“?", "Star Wars", "Star Trek", "Herr der Ringe", "Dune"),
  q("Film & TV", 1, "Wie heißt der gelbe Schwamm aus der Zeichentrickserie?", "SpongeBob Schwammkopf", "Patrick Star", "Thaddäus", "Sandy"),
  q("Film & TV", 1, "Wie heißt der junge Löwe in „Der König der Löwen“?", "Simba", "Mufasa", "Scar", "Nala"),
  q("Film & TV", 1, "Wie heißt der Clownfisch, der im Pixar-Film gesucht wird?", "Nemo", "Dorie", "Marlin", "Flunder"),
  q("Film & TV", 1, "Wie heißt der grüne Oger aus dem DreamWorks-Film?", "Shrek", "Fiona", "Donkey", "Gru"),
  q("Film & TV", 2, "Wer spielte Jack in „Titanic“?", "Leonardo DiCaprio", "Brad Pitt", "Matt Damon", "Johnny Depp"),
  q("Film & TV", 2, "In welcher Stadt spielt die Serie „Friends“?", "New York", "Los Angeles", "Chicago", "Boston"),
  q("Film & TV", 2, "Welcher Schauspieler spielte den ersten Iron Man im Marvel-Universum?", "Robert Downey Jr.", "Chris Evans", "Chris Hemsworth", "Mark Ruffalo"),
  q("Film & TV", 2, "Welcher Hobbit bringt den Ring nach Mordor?", "Frodo Beutlin", "Samweis Gamdschie", "Bilbo Beutlin", "Meriadoc Brandybock"),
  q("Film & TV", 2, "Welche Zeichentrickfamilie lebt in Springfield?", "Die Simpsons", "Die Griffins", "Die Flintstones", "South Park"),
  q("Film & TV", 2, "Wie heißt der Superheld aus Gotham City?", "Batman", "Superman", "Spider-Man", "Iron Man"),
  q("Film & TV", 2, "Welcher Streamingdienst produzierte „Squid Game“?", "Netflix", "Amazon Prime Video", "Disney+", "HBO Max"),
  q("Film & TV", 2, "Welcher Film gewann 2020 den Oscar als bester Film?", "Parasite", "1917", "Joker", "Once Upon a Time in Hollywood"),
  q("Film & TV", 3, "Wer führte Regie bei „Der weiße Hai“?", "Steven Spielberg", "Ridley Scott", "James Cameron", "Martin Scorsese"),
  q("Film & TV", 3, "In welcher Kleinstadt spielt „Stranger Things“?", "Hawkins", "Derry", "Twin Peaks", "Riverdale"),
  q("Film & TV", 3, "Welcher Schauspieler spielt „John Wick“?", "Keanu Reeves", "Liam Neeson", "Jason Statham", "Tom Hardy"),
  q("Film & TV", 3, "Wie heißt der Chemielehrer, der in „Breaking Bad“ zum Drogenkoch wird?", "Walter White", "Jesse Pinkman", "Saul Goodman", "Gus Fring"),
  q("Film & TV", 3, "Wie heißt der Zauberer aus „Der Herr der Ringe“, der grau und später weiß ist?", "Gandalf", "Saruman", "Radagast", "Elrond"),
  q("Film & TV", 3, "In welcher Serie kämpfen Adelshäuser um den Eisernen Thron?", "Game of Thrones", "Vikings", "The Witcher", "The Last Kingdom"),
  q("Film & TV", 3, "Wer moderierte jahrzehntelang „Wetten, dass..?“", "Thomas Gottschalk", "Günther Jauch", "Frank Elstner", "Markus Lanz"),
  q("Film & TV", 3, "Welches Studio produzierte „Toy Story“?", "Pixar", "DreamWorks", "Illumination", "Blue Sky"),
  q("Film & TV", 3, "Wie heißt der Bösewicht in „Der König der Löwen“?", "Scar", "Shere Khan", "Zazu", "Rafiki"),
  q("Film & TV", 3, "Welcher Regisseur drehte „Inception“ und „Interstellar“?", "Christopher Nolan", "Denis Villeneuve", "Quentin Tarantino", "David Fincher"),
  q("Film & TV", 3, "Welche deutsche Netflix-Serie spielt in der Stadt Winden?", "Dark", "Biohackers", "How to Sell Drugs Online (Fast)", "Barbaren"),
  q("Film & TV", 3, "Aus wie vielen Filmen besteht die „Der Herr der Ringe“-Trilogie?", "3", "2", "4", "6"),
  q("Film & TV", 3, "Wie heißt der Droide aus „Star Wars“, der wie eine Mülltonne aussieht?", "R2-D2", "C-3PO", "BB-8", "K-2SO"),
  q("Film & TV", 3, "Auf welchem Mond spielt der Film „Avatar“?", "Pandora", "Arrakis", "Endor", "Titan"),

  /* ---------------- Gaming & Internet ---------------- */
  q("Gaming & Internet", 1, "Wie heißt der berühmte Klempner aus den Nintendo-Spielen?", "Mario", "Luigi", "Link", "Sonic"),
  q("Gaming & Internet", 1, "In welchem Spiel muss man sich vor „Creepern“ in Acht nehmen?", "Minecraft", "Roblox", "Terraria", "Fortnite"),
  q("Gaming & Internet", 1, "Wie heißt das gelbe Elektro-Pokémon?", "Pikachu", "Raichu", "Glumanda", "Evoli"),
  q("Gaming & Internet", 1, "Wie heißt der blaue Igel von Sega?", "Sonic", "Tails", "Knuckles", "Shadow"),
  q("Gaming & Internet", 2, "Welche Firma entwickelt „Fortnite“?", "Epic Games", "Activision", "Ubisoft", "Valve"),
  q("Gaming & Internet", 2, "Welche Konsole brachte Sony 1994 auf den Markt?", "Die PlayStation", "Die Xbox", "Das Nintendo 64", "Den Game Boy"),
  q("Gaming & Internet", 2, "Wofür steht „NPC“ in Videospielen?", "Non-Player Character", "New Player Class", "Network Player Client", "Non-Playable Console"),
  q("Gaming & Internet", 2, "Welche Spielereihe spielt im Königreich Hyrule?", "The Legend of Zelda", "Final Fantasy", "Dark Souls", "Metroid"),
  q("Gaming & Internet", 2, "Welche Livestreaming-Plattform für Games gehört zu Amazon?", "Twitch", "YouTube Gaming", "Kick", "Trovo"),
  q("Gaming & Internet", 2, "Welcher Chat-Dienst ist besonders bei Gamern beliebt?", "Discord", "Slack", "Telegram", "Signal"),
  q("Gaming & Internet", 2, "Welches soziale Netzwerk gehört neben WhatsApp und Facebook zu Meta?", "Instagram", "TikTok", "Snapchat", "X"),
  q("Gaming & Internet", 2, "Wie heißt Nintendos Konsole aus dem Jahr 2017?", "Nintendo Switch", "Wii U", "Nintendo DS", "GameCube"),
  q("Gaming & Internet", 3, "Wer gründete Microsoft zusammen mit Paul Allen?", "Bill Gates", "Steve Jobs", "Steve Ballmer", "Larry Page"),
  q("Gaming & Internet", 3, "Was bedeutet „GG“ im Gaming-Chat?", "Good Game", "Great Gamer", "Go Go", "Got Gold"),
  q("Gaming & Internet", 3, "Welches Studio entwickelt „League of Legends“?", "Riot Games", "Blizzard", "Valve", "Bungie"),
  q("Gaming & Internet", 3, "Was bedeutet „Lag“ in Onlinespielen?", "Eine Verzögerung der Verbindung", "Ein Spielabsturz", "Ein Levelaufstieg", "Ein Cheat"),
  q("Gaming & Internet", 3, "Welches Spiel machte den Battle-Royale-Modus mit 100 Spielern populär?", "PUBG", "Overwatch", "Rust", "Apex Legends"),
  q("Gaming & Internet", 3, "Welche Firma stellt die GeForce-Grafikkarten her?", "Nvidia", "AMD", "Intel", "Qualcomm"),
  q("Gaming & Internet", 3, "Wofür steht „URL“?", "Uniform Resource Locator", "Universal Reference Link", "User Request Line", "Unified Router Location"),
  q("Gaming & Internet", 3, "Welches Unternehmen kaufte YouTube im Jahr 2006?", "Google", "Yahoo", "Microsoft", "Facebook"),
  q("Gaming & Internet", 3, "Welche Shooter-Reihe hat den Untertitel „Modern Warfare“?", "Call of Duty", "Battlefield", "Medal of Honor", "Counter-Strike"),
  q("Gaming & Internet", 3, "Welches Videospiel mit fallenden Blöcken stammt aus der Sowjetunion?", "Tetris", "Pac-Man", "Snake", "Breakout"),
  q("Gaming & Internet", 3, "In welcher fiktiven Stadt spielt „GTA V“?", "Los Santos", "Vice City", "Liberty City", "San Fierro"),
  q("Gaming & Internet", 3, "Was ist ein „Speedrun“?", "Ein Spiel so schnell wie möglich durchspielen", "Ein Rennspielmodus", "Ein Turnier über 24 Stunden", "Ein Sprint-Minispiel"),
  q("Gaming & Internet", 3, "Wie hieß Nintendos Handheld-Konsole von 1989?", "Der Game Boy", "Der Nintendo DS", "Die PSP", "Das Game Gear"),
  q("Gaming & Internet", 3, "Wofür steht die Abkürzung „AFK“?", "Away From Keyboard", "All For Kills", "Away For Knowledge", "After Kill"),

  /* ---------------- Essen & Trinken ---------------- */
  q("Essen & Trinken", 1, "Aus welcher Frucht wird Guacamole hauptsächlich gemacht?", "Avocado", "Gurke", "Zucchini", "Limette"),
  q("Essen & Trinken", 1, "Aus welchem Land stammt die Pizza ursprünglich?", "Italien", "Griechenland", "Spanien", "Frankreich"),
  q("Essen & Trinken", 1, "Welches Gemüse treibt einem beim Schneiden Tränen in die Augen?", "Zwiebel", "Lauch", "Paprika", "Sellerie"),
  q("Essen & Trinken", 1, "Aus welcher Bohne wird Schokolade hergestellt?", "Kakaobohne", "Sojabohne", "Vanillebohne", "Kaffeebohne"),
  q("Essen & Trinken", 2, "Welches Gewürz ist das teuerste der Welt?", "Safran", "Vanille", "Kardamom", "Pfeffer"),
  q("Essen & Trinken", 2, "Woraus wird Sauerkraut hergestellt?", "Weißkohl", "Rotkohl", "Spitzkohl", "Chinakohl"),
  q("Essen & Trinken", 2, "Zu welcher Obstsorte gehört „Granny Smith“?", "Apfel", "Birne", "Pflaume", "Traube"),
  q("Essen & Trinken", 2, "Wie heißt der scharfe grüne japanische Meerrettich?", "Wasabi", "Ingwer", "Miso", "Yuzu"),
  q("Essen & Trinken", 2, "Aus welchem Land stammt Feta-Käse?", "Griechenland", "Italien", "Türkei", "Bulgarien"),
  q("Essen & Trinken", 2, "Von welchem Tier stammt die Milch für original Mozzarella di Bufala?", "Vom Wasserbüffel", "Von der Kuh", "Von der Ziege", "Vom Schaf"),
  q("Essen & Trinken", 2, "Welche Frucht wird auch „Chinesische Stachelbeere“ genannt?", "Kiwi", "Litschi", "Mango", "Papaya"),
  q("Essen & Trinken", 3, "Welches Land produziert weltweit den meisten Kaffee?", "Brasilien", "Kolumbien", "Vietnam", "Äthiopien"),
  q("Essen & Trinken", 3, "Woraus wird Tofu hergestellt?", "Aus Sojabohnen", "Aus Kichererbsen", "Aus Weizen", "Aus Reis"),
  q("Essen & Trinken", 3, "Welche Nudelsorte ist röhrenförmig und schräg abgeschnitten?", "Penne", "Farfalle", "Fusilli", "Tagliatelle"),
  q("Essen & Trinken", 3, "Was ist die Hauptzutat von Hummus?", "Kichererbsen", "Linsen", "Bohnen", "Erbsen"),
  q("Essen & Trinken", 3, "Aus welcher Pflanze wird Tequila hergestellt?", "Aus der Agave", "Aus Zuckerrohr", "Aus Kaktusfeigen", "Aus Mais"),
  q("Essen & Trinken", 3, "Welche Stadt gilt als Heimat der Currywurst?", "Berlin", "Hamburg", "Bochum", "Köln"),
  q("Essen & Trinken", 3, "Wie viel Alkohol hat ein typisches deutsches Pils ungefähr?", "5 %", "8 %", "12 %", "2 %"),
  q("Essen & Trinken", 3, "Aus welchem Getreide besteht Bulgur?", "Weizen", "Hafer", "Gerste", "Hirse"),
  q("Essen & Trinken", 3, "Aus welchem Land stammt Paella?", "Spanien", "Portugal", "Mexiko", "Italien"),
  q("Essen & Trinken", 3, "Wie heißt das japanische Gericht aus rohem Fisch ohne Reis?", "Sashimi", "Sushi", "Maki", "Tempura"),
  q("Essen & Trinken", 3, "Welche Beere gibt Gin sein typisches Aroma?", "Die Wacholderbeere", "Die Holunderbeere", "Die Schlehe", "Die Hagebutte"),
  q("Essen & Trinken", 3, "Welche Käsesorte ist für ihre großen Löcher bekannt?", "Emmentaler", "Gouda", "Camembert", "Cheddar"),
  q("Essen & Trinken", 3, "Woraus wird Marzipan hauptsächlich gemacht?", "Aus Mandeln", "Aus Haselnüssen", "Aus Cashews", "Aus Pistazien"),
  q("Essen & Trinken", 3, "Welches Land ist die Heimat des Gerichts „Gulasch“?", "Ungarn", "Österreich", "Tschechien", "Polen"),

  /* ---------------- Natur & Tiere ---------------- */
  q("Natur & Tiere", 1, "Wie viele Beine hat eine Spinne?", "8", "6", "10", "4"),
  q("Natur & Tiere", 1, "Welches ist das größte Tier der Welt?", "Der Blauwal", "Der Afrikanische Elefant", "Der Weiße Hai", "Die Giraffe"),
  q("Natur & Tiere", 1, "Welches Landtier ist das schnellste?", "Der Gepard", "Der Löwe", "Das Pferd", "Die Antilope"),
  q("Natur & Tiere", 1, "Welches Tier hat den längsten Hals?", "Die Giraffe", "Das Kamel", "Der Strauß", "Das Lama"),
  q("Natur & Tiere", 1, "Welches Insekt produziert Honig?", "Die Biene", "Die Wespe", "Die Hummel", "Die Ameise"),
  q("Natur & Tiere", 1, "Welcher Baum trägt Eicheln?", "Die Eiche", "Die Buche", "Die Birke", "Die Kastanie"),
  q("Natur & Tiere", 1, "Welches Tier trägt seine Jungen in einem Beutel?", "Das Känguru", "Der Waschbär", "Das Faultier", "Der Otter"),
  q("Natur & Tiere", 1, "Was fressen Pandas fast ausschließlich?", "Bambus", "Fisch", "Gras", "Beeren"),
  q("Natur & Tiere", 2, "Wie viele Herzen hat ein Oktopus?", "3", "1", "2", "5"),
  q("Natur & Tiere", 2, "Welches Säugetier kann aktiv fliegen?", "Die Fledermaus", "Das Flughörnchen", "Der Kolibri", "Der Gleitbeutler"),
  q("Natur & Tiere", 2, "Welcher ist der größte Vogel der Welt?", "Der Strauß", "Der Emu", "Der Albatros", "Der Kondor"),
  q("Natur & Tiere", 2, "Wie heißt das Junge eines Pferdes?", "Fohlen", "Kalb", "Lamm", "Welpe"),
  q("Natur & Tiere", 2, "Welches Tier wird auch „Wüstenschiff“ genannt?", "Das Kamel", "Das Zebra", "Die Oryxantilope", "Der Esel"),
  q("Natur & Tiere", 2, "Wie viele Beine hat ein Insekt?", "6", "8", "4", "10"),
  q("Natur & Tiere", 2, "Welche Blume dreht ihre Blüte nach der Sonne?", "Die Sonnenblume", "Die Tulpe", "Die Rose", "Der Mohn"),
  q("Natur & Tiere", 3, "Wie lange dauert die Tragzeit eines Elefanten ungefähr?", "22 Monate", "12 Monate", "9 Monate", "30 Monate"),
  q("Natur & Tiere", 3, "Wie viele Arme hat ein Seestern typischerweise?", "5", "6", "4", "8"),
  q("Natur & Tiere", 3, "Welcher Vogel kann rückwärts fliegen?", "Der Kolibri", "Der Specht", "Die Schwalbe", "Der Falke"),
  q("Natur & Tiere", 3, "Welche ist die größte Katzenart der Welt?", "Der Tiger", "Der Löwe", "Der Jaguar", "Der Leopard"),
  q("Natur & Tiere", 3, "Wie viele Mägen bzw. Magenkammern hat eine Kuh?", "4", "2", "3", "1"),
  q("Natur & Tiere", 3, "Welcher ist der größte Fisch der Welt?", "Der Walhai", "Der Weiße Hai", "Der Blauwal", "Der Mondfisch"),
  q("Natur & Tiere", 3, "Welcher Nadelbaum verliert im Winter seine Nadeln?", "Die Lärche", "Die Fichte", "Die Kiefer", "Die Tanne"),
  q("Natur & Tiere", 3, "Welche Baumart wird am höchsten?", "Der Küstenmammutbaum", "Die Eiche", "Die Douglasie", "Der Eukalyptus"),
  q("Natur & Tiere", 3, "Wie alt können Riesenschildkröten werden?", "Über 100 Jahre", "Etwa 30 Jahre", "Etwa 50 Jahre", "Über 300 Jahre"),
  q("Natur & Tiere", 3, "Wie nennt man ein Tier, das sich nur von Pflanzen ernährt?", "Pflanzenfresser (Herbivore)", "Allesfresser (Omnivore)", "Fleischfresser (Karnivore)", "Aasfresser"),
  q("Natur & Tiere", 3, "Wie heißt die Wissenschaft von den Pflanzen?", "Botanik", "Zoologie", "Ökologie", "Geologie")
];
